### ISSUE TITLE
Drop net6.0 from main

### ISSUE THREAD

**Issue by rmarinho** [dotnet/xharness#1085]
Should we drop net net6.0 multitarget from main?

**Comment by rmarinho** [comment]
net6.0 is EOL no ?

**Comment by akoeplinger** [comment]
We've already dropped net6.0 since we're using `$(NetMinimum)`. I'm dropping netstandard with https://github.com/dotnet/xharness/pull/1134 so I think both of you should be happy :)

**Comment by ViktorHofer** [comment]
> net6.0 is EOL no ?

net6.0 isn't EOL until Nov 2024: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

**Comment by akoeplinger** [comment]
It is for MAUI though which is mostly what xharness is concerned with (modulo WASM): https://dotnet.microsoft.com/en-us/platform/support/policy/maui

**Comment by rmarinho** [comment]
@akoeplinger  one thing I would request is we merge less net9.0 arcade bumps for a while. It breaks if maui doesn't have that runtime/sdk update yet . So for example on main we get a bump that is building our net8.0 fine, but if I merge main to net9.0 now xharness expects a more "modern" sdk/runtime since we are behind ..

**Comment by akoeplinger** [comment]
@rmarinho hmm you should be able to use/install the net8.0 version of xharness in this case.
