### ISSUE TITLE
Add version of the tool in --help

### ISSUE THREAD

**Issue by mandel-macaque** [dotnet/xharness#110]
Print the tool version so that it is easy to know what version of the tool is used when debugging possible problems.

**Comment by premun** [comment]
The version currently comes from Arcade when the package is created so we will need to figure out how to get it before it's created. I will talk to someone from the engineering team about it

**Comment by mandel-macaque** [comment]
@premun that PR has an example on how to do it via refection, since that is set by arcade, is the simplest way :)
