### ISSUE TITLE
global.json causes xharness to be confused about the version

### ISSUE THREAD

**Issue by amirvenus** [dotnet/xharness#1197]
Hi,

I have the following global.json in my solution folder:

```
{
  "sdk": {
    "version": "6.0.100",
    "rollForward": "latestMinor",
    "allowPrerelease": false
  }
}

```

However, when the pipeline runs, I get this error:

You must install .NET to run this application.

App: /Users/build/.dotnet/tools/xharness
Architecture: arm64
App host version: 6.0.29
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=arm64&rid=osx.13-arm64&apphost_version=6.0.29

I can run the xharness through the macOS terminal without any problems. 

```
 dotnet --list-sdks

6.0.100-preview.7.21379.14 [/Users/build/.dotnet/sdk]
6.0.421 [/Users/build/.dotnet/sdk]
8.0.204 [/Users/build/.dotnet/sdk]
```
```

 xharness version
XHarness command issued: version
xharness version 6.0.0-prerelease.24224.2+d1dd9c2ce3fc0b9358d2cda64c52d052d1a612c1 (Microsoft.DotNet.XHarness.CLI.exe)
```

**Comment by ivanpovazan** [comment]
Hello @amirvenus, 

Could you provide more information about your setup?
More specifically, 
> when the pipeline runs

Are you referring to the build pipeline?
 
If yes, can you provide a sample repro project / steps, and possibly a build log: (https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#build-logs / https://msbuildlog.com ) ?

**Comment by ivanpovazan** [comment]
As we did not get any response in the meantime I will close this issue. Please feel free to reopen it if you still experience the same or similar issues.
