### ISSUE TITLE
Questions From a New User

### ISSUE THREAD

**Issue by mrucker** [dotnet/xharness#1238]
I'm a senior .NET developer who has been trying to learn how to use xharness for several days.

- Is there any other documentation beyond the readme file? 
- In lieu of complete hand holding Is there a community site where I could ask questions? 
- Is there a sample application showing how to create an app using the TestRunners that works with xharness CLI? 
- Are the TestRunners available in any package manager?

Any help would be greatly appreciated because I'm fairly certain what you've built is what I've been looking for I'm just struggling to make heads or tails of how to use it.

**Comment by mrucker** [comment]
Here are answers I've found so far:

- Is there any other documentation beyond the readme file? 
   - For xharness as best I can tell the answer is no. For specific testing environments the answer is kind of yes.
   - The Android xharness CLI test command actually uses `adb shell am instrument` to run tests on Android devices. This means more information about test running options can be found [here](https://developer.android.com/studio/test/command-line#run-tests-with-adb) (with a little bit of work to translate between the two). That means, for example, if working in .NET Android land you care about Android.App.Instrumentation.
   - The iOS CLI test command, I'm not sure what its partner is in the iOS world. Hopefully I'll figure it out soon. Why does it matter? Because whatever app development tools you're working in you'll want to know how xharness is going to call your unit tests.
- In lieu of complete hand holding Is there a community site where I could ask questions?
   - Not that I've found
- Is there a sample application showing how to create an app using the TestRunners that works with xharness CLI? 
   - I don't think so. The test runners don't actually work in any given "app" per se. They are pure test runners. Integrating them into any specific app is up to the developer. For example, the MAUI example project inherits from xharness' xunit test runner `AndroidApplicationEntryPoint` to implement their `HeadlessTestRunner` but then write their own `Android.App.Instrumentation` class that calls `HeadlessTestRunner`.
- Are the TestRunners available in any package manager?
   - They are available in NuGet. You have to add the dotnet-eng package source and include prereleases to find them. The source is https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json.

**Comment by ivanpovazan** [comment]
Hello @mrucker!

You are correct on most of the points. Xharness is a testing utility tool developed to make testing .NET applications on mobile platforms (Android, iOS, WebAssembly) easier by utilizing external tools like adb/mlaunch for device communication management. It is mainly used in our testing/CI environments but it can be used in your local environment as well.

The READMEs and the source code is currently afaik the only available documentation. However, we do have a community discord server https://aka.ms/dotnet-discord where you can ask questions in different channels. I would suggest you join us there and post a question in any of the following: #maui, #apple, #android, #webassembly, ... (feel free to ping me - my tag is: ivanpovazan).

**Comment by mrucker** [comment]
Thanks! That's exactly what I was wondering. I thought there might be a discord server. I'm also hoping to use it for testing/CI. Thank you all for making the tool.
