### ISSUE TITLE
Create a `release/9.0` branch a retarget darc

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/xharness#1253]
`dotnet/runtime` and other repos now branched for 10, meaning that their `main` is .NET 10. XHarness should follow suite and create a 9.0 branch and reconfigure darc such that servicing branches for 9.0 get the 9.0 build of XHarness and `main` branches get `main` (that is 10.0 now).
I don't know if we also want to update the version of the XHarness package version itself with this change.

**Comment by akoeplinger** [comment]
> I don't know if we also want to update the version of the XHarness package version itself with this change.

We've followed the .NET versioning in the past, so yes
