### ISSUE TITLE
[apple] Add ability to install a specific simulator runtime version with Xcode 16+

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/xharness#1310]
With Xcode 16 Apple is moving away from hosting newer simulator images publicly: https://developer.apple.com/documentation/xcode/installing-additional-simulator-runtimes#Install-and-manage-Simulator-runtimes-from-the-command-line

Instead for the following simulator versions:
- iOS 16+ (including iPadOS)
- tvOS 16+
- visionOS 1+
- watchOS 9+

they suggest downloading/installing simulator images through `xcodebuild` in the following way:
```
xcodebuild -downloadPlatform iOS -buildVersion <build-version>
```

The `<build-version>` can be acquired from: https://devimages-cdn.apple.com/downloads/xcode/simulators/index2.dvtdownloadableindex under `simulatorVersion` key (either `buildUpdate` or `version` value should work)

Example:
```
<dict>
	<key>authentication</key>
	<string>virtual</string>
	<key>category</key>
	<string>simulator</string>
	<key>contentType</key>
	<string>diskImage</string>
	<key>dictionaryVersion</key>
	<integer>2</integer>
	<key>fileSize</key>
	<integer>7336630623</integer>
	<key>identifier</key>
	<string>com.apple.dmg.iPhoneSimulatorSDK17_5</string>
	<key>name</key>
	<string>iOS 17.5 Simulator Runtime</string>
	<key>platform</key>
	<string>com.apple.platform.iphoneos</string>
	<key>simulatorVersion</key>
	<dict>
		<key>buildUpdate</key>
		<string>21F79</string>
		<key>version</key>
		<string>17.5</string>
	</dict>
	<key>source</key>
	<string>https://download.developer.apple.com/Developer_Tools/iOS_17.5_Simulator_Runtime/iOS_17.5_Simulator_Runtime.dmg</string>
	<key>version</key>
	<string>17.5.0.0</string>
</dict>
```

### Additional note

In the future, if/when we stop supporting older Xcode versions, we should remove code that manually downloads simulator images.

**Comment by jkurdek** [comment]
Is there any reason to keep downloading the older simulator images manually if we can get them using `xcodebuild -downloadPlatform iOS -buildVersion <build-version>`?

**Comment by ivanpovazan** [comment]
>Is there any reason to keep downloading the older simulator images manually if we can get them using CLI?

The feature is only available with Xcode 16.
Older Xcode versions do not support `-downloadPlatform iOS -buildVersion <build-version>` this command.

**Comment by Twoturnttonie** [comment]
- `[](url)`<dict>
	<key>authentication</key>
	<string>virtual</string>
	<key>category</key>
	<string>simulator</string>
	<key>contentType</key>
	<string>diskImage</string>
	<key>dictionaryVersion</key>
	<integer>2</integer>
	<key>fileSize</key>
	<integer>7336630623</integer>
	<key>identifier</key>
	<string>com.apple.dmg.iPhoneSimulatorSDK17_5</string>
	<key>name</key>
	<string>iOS 17.5 Simulator Runtime</string>
	<key>platform</key>
	<string>com.apple.platform.iphoneos</string>
	<key>simulatorVersion</key>
	<dict>
		<key>buildUpdate</key>
		<string>21F79</string>
		<key>version</key>
		<string>17.5</string>
	</dict>
	<key>source</key>
	<string>https://download.developer.apple.com/Developer_Tools/iOS_17.5_Simulator_Runtime/iOS_17.5_Simulator_Runtime.dmg</string>
	<key>version</key>
	<string>17.5.0.0</string>
</dict>
