### ISSUE TITLE
[Android] Provide macOS/Linux support in Xharness CLI

### ISSUE THREAD

**Issue by EgorBo** [dotnet/xharness#135]
Xharness CLI is Windows only for Android at the moment.

**Comment by premun** [comment]
@MattGal is working on this right now actually: https://github.com/dotnet/xharness/pull/129

You can try `1.0.0-prerelease.20229.6`. I am not sure what state it is in but might work on Linux already

**Comment by EgorBo** [comment]
Ah, that's why I didn't find an issue for it 🙂 
@premun @MattGal does it add macOS support as well?

**Comment by premun** [comment]
I don't think it was planned but there is a good chance that if we get ADB for MacOS, it might work

**Comment by mandel-macaque** [comment]
Should work with the mac os x adb, yes.

**Comment by MattGal** [comment]
Adding a usable Linux ADB "just worked" (as in I literally just changed the exe and stuff worked the same) so there's a good chance this will be easy, will do.

**Comment by MattGal** [comment]
Fixed via https://github.com/dotnet/xharness/pull/140
