### ISSUE TITLE
Support running single tests 

### ISSUE THREAD

**Issue by steveisok** [dotnet/xharness#144]
In working w/ xharness, I was trying to run a single test in the same way we do on desktop.  I noticed this feature wasn't support in the way I would expect.  

Most / all of our interaction w/ xharness is going to be triggered via msbuild.  So, given this property, I would like xharness to be able to run a single test:

`/p:XunitMethodName={FullyQualifiedNamespace}.{ClassName}.{TestMethodName}`

**Comment by mandel-macaque** [comment]
@steveisok first step towards that dir: https://github.com/dotnet/xharness/pull/146

**Comment by safern** [comment]
> /p:XunitMethodName={FullyQualifiedNamespace}.{ClassName}.{TestMethodName}

Note that in runtime we transform this to a xunit parameter, `-method {FullyQualifiedNamespace}.{ClassName}.{TestMethodName}`

**Comment by mandel-macaque** [comment]
@steveisok before I get to this, should we just use the format that @safern mentioned? you use case is just for a developer using locally, correct?

**Comment by safern** [comment]
Right the use case is for local debugging or testing to avoid running the whole test suite. This is supported by xunit via the `-method` or `-class` argument. In dotnet/runtime we provide an MSBuild hook via properties as @steveisok mentioned above:

https://github.com/dotnet/runtime/blob/9b5805f9dacee96bac80b2ab10e45e02a9369347/eng/testing/xunit/xunit.console.targets#L19-L20

https://github.com/xunit/xunit/blob/7485b9b3819059dfa810cb5434ebed724be87686/src/xunit.console/ConsoleRunner.cs#L248-L257

**Comment by mandel-macaque** [comment]
Then I think is best to add support for -method and -class, which is easy, and then the msbuild conversion can be reused.
