### ISSUE TITLE
[iOS] mlaunch hangs when XHarness launched by Helix

### ISSUE THREAD

**Issue by premun** [dotnet/xharness#151]
**Environment**
- There are 4 OSX machines with MacOS 10.15.4 and pre-installed Xcode 11.4 and the simulators
- I have a [helix payload](https://github.com/dotnet/xharness/blob/prvysoky%2Fintegration-tests/tests/integration-tests/osx-helix-payload.sh) that I am running from a [test pipeline](https://dev.azure.com/dnceng/public/_build/results?buildId=631666&view=results) using this build step:
```yaml
      - template: /eng/common/templates/steps/send-to-helix.yml
        parameters:
          DisplayNamePrefix: Run Tests
          HelixBaseUri: https://helix.int-dot.net/
          HelixType: test/product/
          IncludeDotNetCli: true
          DotNetCliPackageType: sdk
          DotNetCliVersion: 3.1.201
          WaitForWorkItemCompletion: true
          EnableXUnitReporter: true
          HelixTargetQueues: osx.1015.amd64.ios.open
          Creator: xharness
          WorkItemDirectory: $(Pipeline.Workspace)/Microsoft.DotNet.XHarness.CLI.OSX.IntegrationTests.Debug
          WorkItemCommand: ./osx-helix-payload.sh
          WorkItemTimeout: 00:12:00
```

**Problem**
- The XHarness run times out when calling `mlaunch` on [this line](https://github.com/dotnet/xharness/blob/d6754c4371ac9a9cbe504561f3c2d6242c5af5a9/src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs#L272)
- Stdout from mlaunch says:
```
06:57:16.6555910 /usr/libexec/PlistBuddy -c "Print CFBundleName" /private/tmp/helix/working/AFC2097C/w/A41308E8/e/System.Numerics.Vectors.Tests.app/Info.plist
06:57:16.6840660 /usr/libexec/PlistBuddy -c "Print CFBundleIdentifier" /private/tmp/helix/working/AFC2097C/w/A41308E8/e/System.Numerics.Vectors.Tests.app/Info.plist
06:57:16.6895760 /usr/libexec/PlistBuddy -c "Print UIRequiredDeviceCapabilities" /private/tmp/helix/working/AFC2097C/w/A41308E8/e/System.Numerics.Vectors.Tests.app/Info.plist
06:57:16.6937790 Failed to get the UIRequiredDeviceCapabilities Info.plist property. Assumes 32 bit is not supported
06:57:16.7106450 Test log server listening on: 0.0.0.0:49616
06:57:22.7750200 Found simulator: iPhone X (iOS 13.3) - created by xharness 4D166A7B-709D-45B4-A79D-F52A3CC0CD85
06:57:22.7767710 System log for the 'iPhone X (iOS 13.3) - created by xharness' simulator is: /Users/helix-runner/Library/Logs/CoreSimulator/4D166A7B-709D-45B4-A79D-F52A3CC0CD85/system.log
06:57:22.7772560 *** Executing System.Numerics.Vectors.Tests/Simulator_iOS64 in the simulator ***
06:57:22.8039120 Starting test run
06:57:22.8054240 /Users/helix-runner/.nuget/packages/microsoft.dotnet.xharness.cli/1.0.0-ci/tools/netcoreapp3.1/any/../../../runtimes/any/native/mlaunch/bin/mlaunch -argument=-connection-mode -argument=none -argument=-app-arg:-autostart -setenv=NUNIT_AUTOSTART=true -argument=-app-arg:-autoexit -setenv=NUNIT_AUTOEXIT=true -argument=-app-arg:-enablenetwork -setenv=NUNIT_ENABLE_NETWORK=true -setenv=DISABLE_SYSTEM_PERMISSION_TESTS=1 -v -v -v -v -v -argument=-app-arg:-hostname:127.0.0.1 -setenv=NUNIT_HOSTNAME=127.0.0.1 -argument=-app-arg:-transport:Tcp -setenv=NUNIT_TRANSPORT=TCP -argument=-app-arg:-hostport:49616 -setenv=NUNIT_HOSTPORT=49616 -setenv=NUNIT_ENABLE_XML_OUTPUT=true -setenv=NUNIT_ENABLE_XML_MODE=wrapped -setenv=NUNIT_XML_VERSION=xUnit --launchsim /private/tmp/helix/working/AFC2097C/w/A41308E8/e/System.Numerics.Vectors.Tests.app --stdout=/tmp/helix/working/AFC2097C/w/A41308E8/uploads/mlaunch-stdout-20200505_065722.log --stderr=/tmp/helix/working/AFC2097C/w/A41308E8/uploads/mlaunch-stderr-20200505_065722.log --device=:v2:udid=4D166A7B-709D-45B4-A79D-F52A3CC0CD85
06:57:23.1553850 Using Xcode 11.4 found in /Applications/Xcode.app/Contents/Developer
06:57:23.1605710 Xamarin.Hosting: Xamarin.Hosting
06:57:23.1614440 Xamarin.Hosting:     Version: cec1cba137 (master)
06:57:23.1616060 Xamarin.Hosting:     Xcode: /Applications/Xcode.app
06:57:23.1637960 Xamarin.Hosting:     Xcode Version: 11.4
06:57:23.1647190 Xamarin.Hosting:     Verbosity: 5
06:57:23.1795320 Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/DVTFoundation
06:57:23.1861420 Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTiPhoneSimulatorRemoteClient.framework/DVTiPhoneSimulatorRemoteClient
06:57:23.1864880 Xamarin.Hosting: Loaded /Library/Developer/PrivateFrameworks/CoreSimulator.framework/CoreSimulator
06:57:23.1867710 Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DTDeviceKitBase.framework/DTDeviceKitBase
06:57:23.2090790 Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTKit.framework/DVTKit
06:57:23.2101190 Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DTDeviceKit.framework/DTDeviceKit
06:57:23.2103790 Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DTXConnectionServices.framework/DTXConnectionServices
06:57:23.2124580 Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTSourceControl.framework/DVTSourceControl
06:57:23.2127890 Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTServices.framework/DVTServices
06:57:23.2130050 Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTPortal.framework/DVTPortal
06:57:23.2301420 Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTDocumentation.framework/DVTDocumentation
06:57:23.2312740 Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTAnalyticsClient.framework/DVTAnalyticsClient
06:57:23.2328610 Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTAnalytics.framework/DVTAnalytics
06:57:23.2354600 Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/SourceKit.framework/SourceKit
06:57:23.2660590 Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/IDEFoundation
06:57:23.2676990 Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/IDEProducts.framework/IDEProducts
06:57:23.5068740 Xamarin.Hosting: Simulator watchdogs are already disabled for 'iOS 13.3 (17C45) - iPhone X'.
06:57:23.5186780 Xamarin.Hosting: Launching simulator application 'com.apple.iphonesimulator'
```
- There are no more logs, no device logs (the file doesn't exist yet since it never boots)
- When I
  - SSH into the **same machine**
  - execute the **same job payload**
  - under the **same user**
  - with the **same nupkg** as the one created in the build pipeline
- everything works and `mlaunch` stdout continues like this:
```
07:55:33.6554610 Xamarin.Hosting: Launching simulator application 'com.apple.iphonesimulator'
07:55:34.0035800 Xamarin.Hosting: Ready notification 'com.apple.iphonesimulator.ready' received from the simulator.
07:55:34.0068120 Xamarin.Hosting: Booting iPhone X (iOS 13.3) - created by xharness...
07:55:34.3637440 Xamarin.Hosting: Booted iPhone X (iOS 13.3) - created by xharness successfully.
07:55:34.4382200 Xamarin.Hosting: No need to boot (already booted): iPhone X (iOS 13.3) - created by xharness
07:55:34.4758150 Xamarin.Hosting: Installing /Users/helix-runner/Desktop/tmp/System.Numerics.Vectors.Tests.app with Bundle Identifier net.dot.System.Numerics.Vectors.Tests on 'iOS 13.3 (17C45) - iPhone X'... 07:55:40.8971720 Xamarin.Hosting: Installed 'net.dot.System.Numerics.Vectors.Tests' from /Users/helix-runner/Desktop/tmp/System.Numerics.Vectors.Tests.app
07:55:42.2181320 Xamarin.Hosting: Can't process potentially bad load commands, because the app is signed.
07:55:42.2567600 Xamarin.Hosting: The bundle id net.dot.System.Numerics.Vectors.Tests was successfully installed.
07:55:42.2657210 Xamarin.Hosting: Launching net.dot.System.Numerics.Vectors.Tests on 'iOS 13.3 (17C45) - iPhone X'
07:55:42.3304920 Xamarin.Hosting: Launched net.dot.System.Numerics.Vectors.Tests with pid 2151
07:55:42.3393930 Xamarin.Hosting: Device 'iOS 13.3 (17C45) - iPhone X' booted.
07:55:44.4535310 Connection from 127.0.0.1:50217 saving logs to /Users/helix-runner/Desktop/tmp/tools/o/test-ios-simulator-64-20200505_075531.log
07:55:44.4541670 Test run started
07:55:46.1102740 Tests have finished executing
07:55:46.3407960 Xamarin.Hosting: Simulated process has exited.
```
- I had [one successful run](https://dev.azure.com/dnceng/public/_build/results?buildId=630008&view=logs&j=d5c42908-5572-5ce6-e4a8-5e2053b947e8&t=ff0f581b-ded5-5629-50c0-1f39b9d606b7) when the Simulator was already booted:
```
07:43:57.4552980 Xamarin.Hosting: Device 'iOS 13.3 (17C45) - iPhone X' is already booted and the simulator is running.
07:43:57.4648410 Xamarin.Hosting: No need to boot (already booted): iPhone X (iOS 13.3) - created by xharness
07:43:57.4682210 Xamarin.Hosting: Installing /private/tmp/helix/working/AEF40975/w/AB7609B9/e/System.Numerics.Vectors.Tests.app with Bundle Identifier net.dot.System.Numerics.Vectors.Tests on 'iOS 13.3 (17C45) - iPhone X'...
```

- I tried shutting the Simulator down or letting it be on but I see consistently that manually executed XHarness completes OK and Helix job hangs as described above.

**Comment by MattGal** [comment]
I am stumped too.  I had a theory that the code we use (from proc.py) was blocking something, but that didn't repro when I used the same code to start your script.

My current theory is that this may be related to the python Helix client running as a service.

I think the thing to do is to increase logging to the point of knowing exactly which line fails.

**Comment by MattGal** [comment]
Figured it out.  Still not sure what the fix is.  I discussed briefly with @wfurt and @ulisesh .

What I did
- Took all except dci-mac-build-051 offline
- unloaded the plist file for helix and made sure the client exited
- started the helix client from terminal 
- Sent the representative work you had sent to the machine several times

Workitems:
```
WorkItems
| where JobName in ("e2b05e1d-c504-445c-9508-7e934ed3e525","c527302d-452a-4417-a88a-de741756c107","c2b7e3a3-9d4a-487a-948a-8121936aedd5","d75bc42a-d9ca-4786-9153-232c1d7214bf")
| where Name != JobName
| order by QueueName asc
```

The problem definitely seems to be related to being launched as the child process of a system service.  The open question is whether we have to change the way the LaunchDaemon is set up or whether this can be tweaked in mlaunch (possibly in how you're starting it?)

**Comment by MattGal** [comment]
(we should also use the opportunity to combine our "start a process and get its output" code as there is a lot of duplication here I didn't know about)

**Comment by premun** [comment]
Thanks for looking into this like this! Appreciated!

The problem is that it hangs inside the `mlaunch` binary which is a black box for us a bit. I can try compiling it from `xamarin/maccore`, adding extra logging and running it again.

I will also take a look at how to spawn a process differently and search a bit for the differences.

Thanks again!

**Comment by wfurt** [comment]
In general, running interactive applications in background process is problematic. I don't know if the iPhone simulator is one, but that would be suspect. Maybe elaborate on how to start the simulator and focus on direct execution for now with as little craft as possible. 
Some interactive programs have options for batch or background mode. The other alternative is to execute it using tmux or screen. (or write custom wrapper to allocate pty) 
Aside from that, do you know if any graphic mode is needed?

**Comment by premun** [comment]
So I did a bunch of experimentation and digging and with some pointers from Rolf I found following.

This is a method inside `mlaunch` that makes sure simulator is running and the correct simulator device is booted:

```csharp
public async static Task LaunchAsync (SimDevice device)
{
    if (device.State == DeviceState.Booted && IsSimulatorRunning (device)) {
        Services.Log (2, "Device '{0}' is already booted and the simulator is running.", device.DescriptiveName);
        return;
    }

    var launched = new TaskCompletionSource<bool> ();
    ulong notification_id = 0;
    notification_id = device.RegisterNotificationHandler (DispatchQueue.CurrentQueue, (NSDictionary notification) =>
    {

...
I omitted some checks here that it is the right notification
...

        Services.Log (2, "Device '{0}' booted.", device.DescriptiveName);
    });

    NSError error = null;
    var simulatorBundleId = GetSimulatorBundleId (device);

    var url = NSUrl.FromFilename (GetSimulatorBundlePath (device));
    var configuration = new NSMutableDictionary ();
    configuration.Add (NSWorkspace.LaunchConfigurationArguments, NSArray.FromStrings ("-SessionOnLaunch", "NO"));

    // Observe any ready notifications.
    var ready = new TaskCompletionSource<bool> ();
    var center = (NSDistributedNotificationCenter) NSDistributedNotificationCenter.DefaultCenter;

    NSObject ready_observer = null;
    ready_observer = center.AddObserver ((NSString) GetReadyNotificationName (device), (v) =>
    {

...
THIS PATH IS NEVER HIT AND THE NOTIFICATION IS NEVER RECEIVED
...

        // The simulator is ready
        Services.Log (2, "Ready notification '{0}' received from the simulator.", v.Name);
        if (ready.TrySetResult (true))
            center.RemoveObserver (ready_observer);
        
        if (XcodeLocator.XcodeVersion.Major >= 9)
            Services.BootDevice (device);
    });

    Services.Log ("Launching simulator application '{0}'", simulatorBundleId);
    var app = NSWorkspace.SharedWorkspace.LaunchApplication (url, NSWorkspaceLaunchOptions.Default, configuration, out error);
    if (app == null)
        throw new HostingException (18, MLResources.HE0018, error == null ? "unknown" : error.ToString ());

    await ready.Task;

    if (XcodeLocator.XcodeVersion.Major < 9)
        SendStartSessionNotification (device, 1, 1, launched.Task);

    await launched.Task;
}
```

I left few comments in the code above, but these things happen:
1. We check if the process `Simulator.app` is running (`IsSimulatorRunning`)
2. If it is **AND** our device is booted `=>` we are done
3. If the `Simulator.app` process **is running** but **device is not booted**, we launch the `Simulator.app` and wait for a ready notification (the part where it says `THIS PATH IS NEVER HIT`
4. If we receive ready notification, we boot the device

**What works and what doesn't**
- If I "prelaunch" the correct device manually, the `launchd`-spawned XHarness can find it and use it - then everything works and we get a green run
- Launching the `Simulator.app` process works - we can call `open /path/.../Simulator.app` from the Helix job payload shell script and it opens fine
- `launchd`-spawned `mlaunch` is able to find out if `Simulator.app` is running (confirmed by the first point)
- **BROKEN:** Launching the `Simulator.app` should emit the **ready notification** but we never receive it. It looks like that this might not travel between different sessions (launchd session and some user session where the GUI simulator starts). This might be because Apple are not setting [the NSNotificationPostToAllSessions flag](https://developer.apple.com/documentation/foundation/nsnotificationposttoallsessions?language=objc) when emitting it and there's nothing we can do about it (theory from Rolf)

**Hacky solution to unblock ourselves**
We could change the method above to not launch `Simulator.app` if it is already launched (this check works), but we could only boot the device (not sure if works and has to be tested).
I can make this change locally and try it tomorrow, pointing XHarness to this mlaunch.
However, this solution might break scenarios where multiple different devices would run in parallel. We do not care much about that now but Xamarin might, so.. tricky.

**Proper solution**
Make sure the notifications flow properly by ways suggested by @wfurt or similar, but I am a bit afraid that we just run in a different session and that is a blocker.

**Comment by premun** [comment]
@mandel-macaque @MattGal I can pre-boot the simulators on the 4 OSX machines and add integration tests to our PRs. It is a bit hacky and not solid but hopefully they won't crash so this could work for us for the time being.

**Comment by MattGal** [comment]
> @mandel-macaque @MattGal I can pre-boot the simulators on the 4 OSX machines and add integration tests to our PRs. It is a bit hacky and not solid but hopefully they won't crash so this could work for us for the time being:
> https://dev.azure.com/dnceng/public/_build/results?buildId=633240&view=results

As long as it's reliable (survives device reboot, etc) that's a fine workaround for me.

**Comment by premun** [comment]
Looks like @mandel-macaque has a fix for this, utilizing `sudo launchctl asuser`.

However, there are some issues with the listeners now. I will investigate those

**Comment by premun** [comment]
@mandel-macaque this is still happening 😥 looks like if I don't log on to the machine for some time, the machine loses the GUI user session or something like that and then it starts happening again..

**Comment by MattGal** [comment]
@ilyas1974 may have some context and suggestions here.  We've had stuff in place to make sure the macs are logged in to an interactive session in the past for other reasons (Docker?)

**Comment by ilyas1974** [comment]
@MattGal is correct - the systems should be auto logging in to an interactive session for docker. Do you have an example of system with this problem so I can take a closer look at what is going on with the system?

**Comment by premun** [comment]
This seems to be resolved by killing the Simulator.app and then starting it again:
https://github.com/dotnet/xharness/commit/c6fd4f291bfc2a8dfb7d46577959e3a9ba0fa132
