### ISSUE TITLE
Enable nullable references

### ISSUE THREAD

**Issue by premun** [dotnet/xharness#16]
We can consider turning on nullable references which would totally make sense at least for the CLI project where we really care for arguments to be set properly. Other projects could follow.
For iOS.Shared it might be a problem to enable it for the whole project at once since it's quite large but we can definitely try it and see. It would also make sense there because we really care about proper flow of arguments from the CLI to mlaunch and similar.

**Comment by premun** [comment]
@MattGal we have spoken about this with @mandel-macaque briefly on Friday and we agree that we would be up for trying this out. Your thoughts?

**Comment by premun** [comment]
I had a first stab over the weekend at this and it gets really tricky with the MonoOptions parsing.

**Comment by MattGal** [comment]
> @MattGal we have spoken about this with @mandel-macaque briefly on Friday and we agree that we would be up for trying this out. Your thoughts?

I think it's fancy technology for fancy technology's sake, and maybe not the best use of your time.  But if you're doing it, go for it!

**Comment by premun** [comment]
That's why I did it on my own time since it is mostly my curiosity. But I disagree it's for fancy technology's sake. There is a lot of value in it that prevents a really nasty class of runtime errors. I think for us it might be even more important since this is not a service and we do not collect logs from the usage of the tool so if it crashes for people, it might be hard to repro.

After turning it on it already showed me bugs in the CLI that would result in crashes.

**Comment by MattGal** [comment]
Sure.  It sounds like the kind of thing that's cheaper to do now than later...
