### ISSUE TITLE
If instrumentation crashes xharness exits with code 0

### ISSUE THREAD

**Issue by safern** [dotnet/xharness#177]
For example, I have an instrumentation that crashed:

```
05-12 17:57:09.386  2027  4471 I ActivityManager: Process net.dot.System.Runtime.Tests (pid 13396) has died: fore FGS 
05-12 17:57:09.386  1781  1781 I Zygote  : Process 13396 exited due to signal 11 (Segmentation fault)
05-12 17:57:09.387  2027  2058 I libprocessgroup: Successfully killed process cgroup uid 10148 pid 13396 in 0ms
05-12 17:57:09.387  2027  4471 W ActivityManager: Crash of app net.dot.System.Runtime.Tests running instrumentation ComponentInfo{net.dot.System.Runtime.Tests/net.dot.MonoRunner}
```

and this is the Xharness output:
```
  info: test[0]
        Running instrumentation class net.dot.MonoRunner took 54.0933972 seconds
  info: test[0]
        Wrote current ADB log to /Users/santifdezm/repos/runtime/artifacts/bin/System.Runtime.Tests/net5.0-Unix-Debug/android-x86/AppBundle/TestResults/adb-logcat-net.dot.System.Runtime.Tests.log
  info: test[0]
        Attempting to remove apk 'net.dot.System.Runtime.Tests': 
  info: test[0]
        Successfully uninstalled net.dot.System.Runtime.Tests.
  XHarness exit code: 0
```

cc: @MattGal @EgorBo @steveisok @akoeplinger

**Comment by MattGal** [comment]
Discussed offline, there is a result property bag for exit code set but this is only if that code runs;  XHarness already will fail for any non-0 exit code from the instrumentation itself, so we'll chat about solutions in the AM but this likely is something that has to be fixed in the instrumentation class.

**Comment by safern** [comment]
I think this is different than what we discussed. Here the Instrumentation crashed, so we didn't exit, if you look at the logs on a crash there is not even a exit code.

**Comment by safern** [comment]
So @MattGal and I took a deeper look at this and it seems like when there is an unhandled exception the test runner we have handles it and calls `exit(1)`:

https://github.com/dotnet/runtime/blob/5859dadf20a9dae44624e0a79e48f1b3f1f26a0a/src/mono/msbuild/AndroidAppBuilder/Templates/runtime-android.c#L111-L125

So we don't get to call `finish` on the `Instrumentation` and the logs suggest that the app did exit with exit code 1 but something is changing it to 0 when the instrumentation returns and XHarness can't see it. We call `finish` here: https://github.com/dotnet/runtime/blob/5859dadf20a9dae44624e0a79e48f1b3f1f26a0a/src/mono/msbuild/AndroidAppBuilder/Templates/MonoRunner.java#L60 -- but in this case I'm pretty sure that is not executed because we failed fast and the logs suggest that:

```
05-13 15:20:38.896 23671 23691 E mono    : Unhandled Exception:
05-13 15:20:38.896 23671 23691 E mono    : System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
05-13 15:20:38.896 23671 23691 E mono    :    at SimpleAndroidTestRunner.Main(String[] args) in /Users/santifdezm/repos/runtime/src/libraries/Common/tests/AndroidTestRunner/AndroidTestRunner.cs:line 42
05-13 15:20:38.896 23671 23691 E mono    :    at SimpleAndroidTestRunner.<Main>(String[] args)
05-13 15:20:38.896 23671 23691 E DOTNET  : UnhandledException: System.OutOfMemoryException Insufficient memory to continue the execution of the program.    at SimpleAndroidTestRunner.Main(String[] args) in /Users/santifdezm/repos/runtime/src/libraries/Common/tests/AndroidTestRunner/AndroidTestRunner.cs:line 42
05-13 15:20:38.896 23671 23691 E DOTNET  :    at SimpleAndroidTestRunner.<Main>(String[] args)
05-13 15:20:38.973  2027  2946 I ActivityManager: Process net.dot.System.Net.Requests.Tests (pid 23671) has died: fore FGS 
05-13 15:20:38.973  1781  1781 I Zygote  : Process 23671 exited cleanly (1)
05-13 15:20:38.973  2027  2058 I libprocessgroup: Successfully killed process cgroup uid 10184 pid 23671 in 0ms
05-13 15:20:38.974  2027  2946 W ActivityManager: Crash of app net.dot.System.Net.Requests.Tests running instrumentation ComponentInfo{net.dot.System.Net.Requests.Tests/net.dot.MonoRunner}
05-13 15:20:38.974  2027  2946 I ActivityManager: Force stopping net.dot.System.Net.Requests.Tests appid=10184 user=0: finished inst
05-13 15:20:38.975  2027 23827 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
05-13 15:20:38.975  2027 23827 W Binder  : java.lang.Throwable
05-13 15:20:38.975  2027 23827 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
05-13 15:20:38.975  2027 23827 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
05-13 15:20:38.975  2027 23827 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
05-13 15:20:38.976 23657 23657 D AndroidRuntime: Shutting down VM
```

@akoeplinger @EgorBo any ideas on what might be changing the exit code to 0 or how to propagate the crash to xharness? @MattGal was thinking that we could have a contract that the runners should set `return-code` property bag in the bundle result, if that is not set, that means it hung or crashed.

**Comment by MattGal** [comment]
I had actually baked in reliance on `return-code` but removed it when I saw the runtime PR for exit codes.  I will make this required and fail if it's not in the property bag of a given instrumentation, since we absolutely cannot tolerate ignoring crashes.  From discussing with @akoeplinger this seems like the simplest solution moving forward.

**Comment by akoeplinger** [comment]
This was addressed with https://github.com/dotnet/xharness/pull/190
