### ISSUE TITLE
Figure out verbosity setting

### ISSUE THREAD

**Issue by premun** [dotnet/xharness#19]
- In iOS part of XHarness and also in mlaunch, verbosity is set via `-v` option that can be provided multiple times and an `int` verbosity level is set and used.
The way it is being passed around is also a bit unfortunate because it is handed over in method args/ctors even though it's a quite static property of the program run.

- In the CLI we have now `ILogger` which has `Debug`/`Information`/`Warning`. I am not sure what is the mechanism to set that but I assume there will be one soon.

**Proposal**
1. It would be nice to have some static global place with verbosity setting for the run that we can access from within the iOS code (or if that's too ugly, we can have it in `ICommandArguments`)
2. It would be nice to have it in a way that both `ILogger` and `mlaunch` understand it

**Comment by MattGal** [comment]
I'll be taking a stab at this as part of my current work.
