### ISSUE TITLE
[Runners] The SkipTestException tests are considered a failure in the xml result

### ISSUE THREAD

**Issue by mandel-macaque** [dotnet/xharness#205]
We added a fix to do not count the tests that raise a SkipTestException as a failure but as a Skip. The issue with that fix is that it just focused in the the handler, but not the actual test results. 

Once everything has been ran, and xunit is used, xharness parses the results, and marks the build as a failure. The correct way to fix this is to modify the runner to use a correct test sink that **does not** communicate those tests as failures.

The dotnet team already does that:  https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.XUnitExtensions/src/SkippedFactTestCase.cs#L31 and https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.XUnitExtensions/src/SkippedTestMessageBus.cs#L19

Probably means we will need to use a new sink here: https://github.com/dotnet/xharness/blob/master/src/Microsoft.DotNet.XHarness.Tests.Runners/xUnit/XUnitTestRunner.cs#L49

**Comment by safern** [comment]
fyi: @steveisok

**Comment by mandel-macaque** [comment]
Closing after a conversation with @safern and @akoeplinger about the other route that will be taken.
