### ISSUE TITLE
XHarness exits with code 1 during iOS testing even with test suite skip

### ISSUE THREAD

**Issue by mdh1418** [dotnet/xharness#258]
Adding an assembly level active issue to skip a test suite leads to a build failure of `XHarness exit code: 1`

Expectation:
Tests skipped and build succeeds

Repro:
Add an `AssemblyInfo.cs` file to `src/libraries/System.Globalization/tests/`

```// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System;
using Xunit;

[assembly: ActiveIssue("https://github.com/dotnet/runtime/issues/36883", TestPlatforms.iOS)]
```

and `<Compile Include="AssemblyInfo.cs" />` to 
`src/libraries/System.Globalization/tests/System.Globalization.Tests.csproj`

Build and run the iOS test suite [testing workflow](https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/libraries/testing-apple.md)
```
<runtime-repo>/build.sh mono+libs -os iOS -arch x64
cd src/libraries/System.Globalizatio/tests/
<runtime-repo>/dotnet.sh build /t:Test /p:TargetOS=iOS /p:TargetArchitecture=x64 /p:DevTeamProvisioning=UBF8T346G9
```

The test build 
[iPhone X (iOS 13.4) - created by xharness.log](https://github.com/dotnet/xharness/files/4761036/iPhone.X.iOS.13.4.-.created.by.xharness.log)
[run-Simulator_iOS64.log](https://github.com/dotnet/xharness/files/4761037/run-Simulator_iOS64.log)
[simulator-list-20200610_161005.log](https://github.com/dotnet/xharness/files/4761038/simulator-list-20200610_161005.log)
[test-ios-simulator-64-20200610_161005.log](https://github.com/dotnet/xharness/files/4761039/test-ios-simulator-64-20200610_161005.log)
[System.Globalization.Tests.app.zip](https://github.com/dotnet/xharness/files/4761041/System.Globalization.Tests.app.zip)

**Comment by premun** [comment]
@akoeplinger I am a bit confused about the `[ActiveIssue]` attribute - I thought this could be handled by the trait files on your end and hence this https://github.com/dotnet/xharness/pull/255?

**Comment by premun** [comment]
Oh, I get it - it does skip it correctly, but XHarness returns 1.. Will fix it ASAP

**Comment by premun** [comment]
@mdh1418 fix is here: https://github.com/dotnet/xharness/pull/262

**Comment by premun** [comment]
@mdh1418 if you will update to version **1.0.0-prerelease.20311.4** and later, it has the fix inside
