### ISSUE TITLE
[iOS] mlaunch takes long time to list Simulator devices

### ISSUE THREAD

**Issue by premun** [dotnet/xharness#283]
We retry listing simulators 3 times but it fails each time with:
```
[07:24:10] dbug: test[0]
      07:24:10.2202860 Failed to find/create simulator (attempt 3/3):
      System.Exception: Failed to list simulators - no XML with devices found. mlaunch timed out with 137)
         at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.SimulatorLoader.LoadDevices(ILog log, Boolean includeLocked, Boolean forceRefresh, Boolean listExtraData) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs:line 80
         at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.SimulatorLoader.FindOrCreateDevicesAsync(ILog log, String runtime, String devicetype, Boolean force) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs:line 211
         at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.SimulatorLoader.FindSimulators(TestTargetOs target, ILog log, Boolean createIfNeeded, Boolean minVersion) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs:line 385
         at Microsoft.DotNet.XHarness.iOS.AppRunner.RunApp(AppBundleInformation appInformation, TestTargetOs target, TimeSpan timeout, TimeSpan testLaunchTimeout, String deviceName, String companionDeviceName, Boolean ensureCleanSimulatorState, Int32 verbosity, XmlResultJargon xmlResultJargon, String[] skippedMethods, String[] skippedTestClasses, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs:line 115
[07:24:10] fail: test[0]
      Failed to find suitable device for target ios-simulator-64_13.5
      Please make sure suitable Simulator is installed in Xcode
```

Examples:
- https://helix.dot.net/api/2019-06-17/jobs/6c7f20d9-ef8a-4adc-a37c-5be927b1ea61/workitems/System.Numerics.Vectors.Tests/console
- https://helix.dot.net/api/2019-06-17/jobs/503c156a-1c2c-4e78-9581-941d6cde7ab8/workitems/System.Numerics.Vectors.Tests/console
- https://helix.dot.net/api/2019-06-17/jobs/d6aa791c-9e38-4f50-ad3c-ef51d2f46678/workitems/System.Numerics.Vectors.Tests/console
- https://helix.dot.net/api/2019-06-17/jobs/8bd40904-b285-4037-b186-77116beaf3fc/workitems/System.Numerics.Vectors.Tests/console

Happens on various machines but from what I observed (I might be wrong though), these keep popping up:
- `dci-mac-build-136`
- `dci-mac-build-138`
- `dci-mac-build-142`
- `dci-mac-build-147`

**Comment by premun** [comment]
This seems to be happening still:
- https://helix.dot.net/api/2019-06-17/jobs/943f0a60-00f1-4b2e-8b4e-127603079422/workitems/Microsoft.Extensions.Configuration.Ini.Tests/console
- https://helix.dot.net/api/2019-06-17/jobs/943f0a60-00f1-4b2e-8b4e-127603079422/workitems/System.Net.ServicePoint.Tests/console
- https://helix.dot.net/api/2019-06-17/jobs/943f0a60-00f1-4b2e-8b4e-127603079422/workitems/System.Threading.Tasks.Parallel.Tests/console

happened on:
- `dci-mac-build-136`
- `dci-mac-build-144`
- `dci-mac-build-145`

**Comment by premun** [comment]
So looks like these machines fail:
- `dci-mac-build-136`
- `dci-mac-build-137`
- `dci-mac-build-138`
- `dci-mac-build-141`
- `dci-mac-build-142`
- `dci-mac-build-143`
- `dci-mac-build-144`
- `dci-mac-build-145`
- `dci-mac-build-146`
- `dci-mac-build-147`
- `dci-mac-build-148`

I will try to reproduce there and see what's up

**Comment by premun** [comment]
Still happening about 5% off the runs:
```
mlaunch --sdkroot /Applications/Xcode115.app --listsim=/tmp/tmpDE6r10.tmp --output-format=XML
```

This times out even though I increased it to 1 minute as compared to Xamarin macios where it is 30 seconds.
It times out 3 times in a row and then the build fails.
Sometimes it times out but leaves the result XML behind but that we can handle already.

**Comment by premun** [comment]
I have found the root cause:
1. When listing of Simulator devices would fail for some reason (timeout which was set to 30 seconds), we would mark `SimulatorLoader` as `loaded` but no devices where in the memory.
2. Since no devices would fit our requirements when running a test, we would create a new iOS Simulator device. There would probably be a duplicate one that we have created previously already but we wouldn't know.

This starts a viscous circle of:
- Loading devices now takes a little bit longer with more devices to enumerate -> increasing the chance that it would time out again.
- With increasing probability of failure (timeout), we create a new device for each failure, increasing the probability even more until some machines get cluttered with duplicate devices.
- With about 15-20 devices the `xcrun simctl list devices` command takes about 3-4 minutes to complete and mlaunch times out at every attempt from there.

The issue described above was fixed here: https://github.com/dotnet/xharness/pull/288

I have triggered a clean-up job **44cae37f-da60-4291-812e-d6da1e772811** that will remove all devices created by XHarness by running:
```
sudo xcrun simctl list devices | grep 'created by XHarness' | grep -Eo '[A-Z0-9]+\-[A-Z0-9]+\-[A-Z0-9]+\-[A-Z0-9]+\-[A-Z0-9]+' | xargs -t sudo xcrun simctl delete
```

**Comment by premun** [comment]
Seems to be still happening...

**Comment by premun** [comment]
Through investigation, I learned that it helps to reduce the number of Simulator devices (instances of phone chassis + runtime - say iPhone 11 - iOS 13.5), so I have removed all devices from all machines and [added](https://dev.azure.com/dnceng/internal/_build/results?buildId=777686) that to our `macos-xcode` artifact.

- I found out that some machines just take longer (2-4 minutes) than other machines by removing some from the pool and running a high number of tests.
- I also found that subsequent calls usually take way less time as if there was some kind of a cache in place

I still don't understand why this is for some machines and what is different. Most likely the cache gets erased by us terminating the Simulators or something similar. There is almost no official documentation on the `simctl` command

**Comment by akoeplinger** [comment]
We also hit a similar issue today where we got `System.Exception: Failed to list simulators - no XML with devices found. mlaunch exited with 1)`.

It turned out that we were using an old xharness/mlaunch in a servicing branch that wasn't compatible with Xcode 14 so mlaunch crashed.

Just posting this here so it shows up in search :D
