### ISSUE TITLE
xharness sometimes doesn't parse the return-code

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/xharness#338]
Example test run: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43804-merge-9c3fe24fa96341daa0/System.Xml.RW.FactoryReader.Tests/console.c6b2c6e3.log

It says:
```
04:16:56] info: Starting instrumentation class 'net.dot.MonoRunner' on net.dot.System.Xml.RW.FactoryReader.Tests
[04:16:56] dbug: Raw command: 'shell am instrument  -w net.dot.System.Xml.RW.FactoryReader.Tests/net.dot.MonoRunner'
[04:16:56] dbug: Executing command: '/home/helixbot/work/B3070977/p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.20519.2/runtimes/any/native/adb/linux/adb -s emulator-5556 shell am instrument  -w net.dot.System.Xml.RW.FactoryReader.Tests/net.dot.MonoRunner'
[04:17:21] info: Running instrumentation class net.dot.MonoRunner took 25.140556 seconds
[04:17:21] dbug: Exit code: 0
                 Standard Output:
                 
                 
[04:17:21] fail: No value for 'return-code' provided in instrumentation result.  This may indicate a crashed test (see log)
```

However if you look at the adb log you see that the test run completed successfully and we returned the correct `return-code` key:
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43804-merge-9c3fe24fa96341daa0/System.Xml.RW.FactoryReader.Tests/adb-logcat-net.dot.System.Xml.RW.FactoryReader.Tests.log

```
10-27 04:17:20.099  4349  4370 I DOTNET  : Xml file was written to the provided writer.
10-27 04:17:20.110  4349  4370 I DOTNET  : Tests run: 2292 Passed: 2292 Inconclusive: 0 Failed: 0 Ignored: 0
10-27 04:17:20.114  4349  4370 I DOTNET  : ----- Done -----
10-27 04:17:20.134  4349  4366 D DOTNET  : Exit code: 0.
10-27 04:17:20.134  4349  4366 I DOTNET  : MonoRunner finished, return-code=0
10-27 04:17:20.135  4349  4366 I DOTNET  : MonoRunner finished, test-results-path=/storage/emulated/0/Android/data/net.dot.System.Xml.RW.FactoryReader.Tests/files/Documents/testResults.xml
```

This means either xharness doesn't parse the stdout of adb correctly, or adb doesn't print it?

/cc @MattGal @steveisok

**Comment by akoeplinger** [comment]
The issue is probably somewhere here:

https://github.com/dotnet/xharness/blob/e26ccfae0b1a38add2abb04104e4666c9b011d82/src/Microsoft.DotNet.XHarness.Android/Execution/AdbProcessManager.cs#L70-L84

The presence of the locks indicate to me that we hit a case where it was still writing to the stdout StringBuilders even after the 1 second timeout, which could mean we missed some events.

Comparing the code with some other Process code I think we're missing at least a call to `Process.Close()` and more importantly another call to the parameter-less `Process.WaitForExit()` since the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.waitforexit?view=netcore-3.1#System_Diagnostics_Process_WaitForExit) state:
> This overload ensures that all processing has been completed, including the handling of asynchronous events for redirected standard output. You should use this overload after a call to the WaitForExit(Int32) overload when standard output has been redirected to asynchronous event handlers.

**Comment by jkoritzinsky** [comment]
dotnet/runtime issue https://github.com/dotnet/runtime/issues/43983 is tracking this issue.

**Comment by akoeplinger** [comment]
Seems to be fixed now.
