### ISSUE TITLE
[iOS] Recognize the successful run of mono sample application

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/xharness#363]
This is related to https://github.com/dotnet/runtime/issues/43865.

Xharness is used to run runtime library tests on iOS simulator/device. This way we could run the mono samples (iOS, in particular) in order to make sure that they work. Some work to incorporate the sample into library test build has been done in https://github.com/dotnet/runtime/pull/44462. The problem at the moment is that xharness <s>fails to run the sample app</s> can run the sample app successfully 
```
dbug: 13:23:00.1491670 Xamarin.Hosting: Launched net.dot.HelloiOS with pid 55778
dbug: 13:23:08.1533420 Xamarin.Hosting: Simulated process has exited.
dbug: 13:23:08.4415320 Process exited with 0
```
but it still finishes with non-zero exit code because it expects some things specific to running tests not just apps. 
```
info: Application finished the test run successfully with some failed tests
info: No test log file was produced
XHarness exit code: 1
```

So one of the options could be to return some particular exit code (e.g. 42 ) in the ios sample C# main method and update xharness to understand that this means the sample app run successfully.

**Comment by MaximLipnin** [comment]
cc/  @premun  @akoeplinger

**Comment by akoeplinger** [comment]
I think the main point is that we shouldn't assume an iOS app will have xunit/nunit tests in it, but instead just have a normal C# Main() that returns an exit code.

**Comment by premun** [comment]
I think this issue is a mix of 2 things that need to happen. We will split this effort with Katya. I created 2 issues that describe what needs to be done: #364 and #365.

Closing this one.
