### ISSUE TITLE
Detect exit code of iOS apps

### ISSUE THREAD

**Issue by premun** [dotnet/xharness#364]
**Context**
Currently, XHarness and mlaunch are unable to detect exit code of the iOS app that was spawned.
For scenarios where we don't have a TestRunner inside of the application, we have no information about the app run at all.

**Goal**
We should investigate if this is easy to do. Rolf confirmed that this was hard to do reliably across all iOS versions but we might just start doing it from the current one and see.

The way it can be done currently is from system logs of the device which we capture already.
We should use the `IErrorKnowledgeBase` strategy to scan for following lines in the device logs:

```
Nov 16 14:03:39 ML-MacVM com.apple.CoreSimulator.SimDevice.2E1EE736-5672-4220-89B5-B7C77DB6AF18[55655] (UIKitApplication:net.dot.HelloiOS[9a0b][rb-legacy][57331]): Service exited with abnormal code: 200
```

The important parts are the namespace of the app bundle which we know (**net.dot.HelloiOS**) and the message line itself.

**Comment by premun** [comment]
@MaximLipnin the detection of exit code via system log won't work for iOS devices but only for simulators. This is because system log from device is streamed from the device via the TestRunner. So it looks like it will be an incomplete solution. Is this good enough for your scenarios?

**Comment by MaximLipnin** [comment]
I think it's fine for now to have something work for simulators only. At least it will allow us to build the entire flow where the mono ios sample is incorporated. 
@akoeplinger What do you think?

**Comment by premun** [comment]
Ah, sorry, it is possible to pull device logs via mlaunch actually. I will dig into this more..

**Comment by premun** [comment]
Will keep this opened until we get the SDK changes in
