### ISSUE TITLE
CLI for running Android tests should allow specifying API level

### ISSUE THREAD

**Issue by mattleibow** [dotnet/xharness#380]
It would be nice to be able to specify some API level which will then provide a filter for selecting the emulator.

**Comment by premun** [comment]
cc @MattGal

**Comment by tkapin** [comment]
@mattleibow - could you please describe what is the value of this and what problems this would solve? thanks!

**Comment by mattleibow** [comment]
This will be useful if there are multiple emulators running, then it could pick the correct one.

The real value in this is when testing with Android APIs. Each version has quite a different feature set and often there are breaking changes. One example is the storage privacy.

I suppose really the current case of waiting when multiple emulators are running stops all this, but it will be nice to be able to determine one and use it.

Also, this goes with https://github.com/dotnet/xharness/issues/393 in that if it can boot emulators like it does with iOS, then this will help.

**Comment by greenEkatherine** [comment]
There should be the same logic that we use for choosing architecture or emulator where app was already installed. I think, API level could be easily retrieved by calling some property request similar to architecture check.
