### ISSUE TITLE
Failing launches on older (API 23) Android emulators

### ISSUE THREAD

**Issue by mattleibow** [dotnet/xharness#384]
I have a few runs on API 30, 29, 26, and 23. I get a good run on all each time, except for API 23. I randomly get a failure on DevOps (using the default hosted agents), but it appears to work locally.

Logcat:

[adb-logcat-com.microsoft.azure.devicetests (3).log](https://github.com/dotnet/xharness/files/5609733/adb-logcat-com.microsoft.azure.devicetests.3.log)

Console log:

```
info: Starting instrumentation class 'com.microsoft.azure.devicetests.TestInstrumentation' on com.microsoft.azure.devicetests
dbug: Raw command: 'shell am instrument  -w com.microsoft.azure.devicetests/com.microsoft.azure.devicetests.TestInstrumentation'
dbug: Executing command: '/Users/runner/.dotnet/tools/.store/microsoft.dotnet.xharness.cli/1.0.0-prerelease.20575.2/microsoft.dotnet.xharness.cli/1.0.0-prerelease.20575.2/runtimes/any/native/adb/macos/adb -s emulator-5554 shell am instrument  -w com.microsoft.azure.devicetests/com.microsoft.azure.devicetests.TestInstrumentation'
info: Running instrumentation class com.microsoft.azure.devicetests.TestInstrumentation took 0.255454 seconds
dbug: Exit code: 0
      Standard Output:
      
      
fail: No value for 'return-code' provided in instrumentation result.  This may indicate a crashed test (see log)
dbug: Executing command: '/Users/runner/.dotnet/tools/.store/microsoft.dotnet.xharness.cli/1.0.0-prerelease.20575.2/microsoft.dotnet.xharness.cli/1.0.0-prerelease.20575.2/runtimes/any/native/adb/macos/adb -s emulator-5554 logcat -d '
info: Wrote current ADB log to /Users/runner/work/1/s/output/test-results/android/adb-logcat-com.microsoft.azure.devicetests.log
info: Attempting to remove apk 'com.microsoft.azure.devicetests': 
dbug: Executing command: '/Users/runner/.dotnet/tools/.store/microsoft.dotnet.xharness.cli/1.0.0-prerelease.20575.2/microsoft.dotnet.xharness.cli/1.0.0-prerelease.20575.2/runtimes/any/native/adb/macos/adb -s emulator-5554 uninstall com.microsoft.azure.devicetests'
info: Successfully uninstalled com.microsoft.azure.devicetests.
fail: Non-success instrumentation exit code: 82, expected: 0
XHarness exit code: 71
```

**Comment by mattleibow** [comment]
I am just running a test on which APIs exactly fail... Will keep everyone posted for these old boys!

**Comment by mattleibow** [comment]
I think it starts on API 24. I did a retry and now it is working... This _should_ be on a fresh image, but sometimes it fails. Not sure why it gets inconsistent.

**Comment by premun** [comment]
@mattleibow we were able to run 12 000 apps yesterday and today without issues on APIs 21-32.

Maybe this was a fluke or a bad app?

**Comment by tkapin** [comment]
This issue was logged such long time ago (almost 1.5 years) that the infrastructure is probably completely different now. As Premek says, this is not observed anymore. I'm closing this one, @mattleibow - please feel free to reopen if you see this issue still manifesting somewhere.

**Comment by mattleibow** [comment]
Oof, this is an old one. And yep, we are running fine on 23 once again
