### ISSUE TITLE
What is the correct "test-results-path" value for Android?

### ISSUE THREAD

**Issue by mattleibow** [dotnet/xharness#385]
I have tried a few places, but it seems xharness can't access the files:

I am trying this now:
`Application.Context.GetExternalFilesDir(null)?.AbsolutePath`

```
info: Attempting to pull contents of /storage/emulated/0/Android/data/com.microsoft.azure.devicetests/files/Documents/TestResults.xml to /Users/runner/work/1/s/output/test-results/android
dbug: Executing command: '/Users/runner/.dotnet/tools/.store/microsoft.dotnet.xharness.cli/1.0.0-prerelease.20575.2/microsoft.dotnet.xharness.cli/1.0.0-prerelease.20575.2/runtimes/any/native/adb/macos/adb -s emulator-5554 pull /storage/emulated/0/Android/data/com.microsoft.azure.devicetests/files/Documents/TestResults.xml /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/ae3z53fb.5bv'
fail: ERROR: Exit code: 1
      Standard Output:
      adb: error: failed to stat remote object '/storage/emulated/0/Android/data/com.microsoft.azure.devicetests/files/Documents/TestResults.xml': Permission denied
```

And another thing is that the failed pull does _not_ actually fail the command. I still get a 0 return code and so all my builds were passing. I only noticed when I was looking for the results.

**Comment by MattGal** [comment]
@mattleibow in the earliest versions of XHarness Android support, I would set up permissions to arbitrary paths and use these.  Currently, there's not actually any attempt to do this; the permission AFAIK (@steveisok please comment) comes from the APK itself, then the instrumentation passes back the path(s) to be pulled via key-value pair like you've noted e.g.:

```
test-results-path=/storage/emulated/0/Android/data/net.dot.System.Xml.Xsl.XslCompiledTransformApi.Tests/files/Documents/testResults.xml
```
The reason this is passing (can certainly make this error out in the case where the pull fails... just an oversight) is that the return code key value pair (like `return-code=0` in instrumentation results) contains the "success" exit code value.

I'm doing another fix for XHarness Android stuff today and I can make this an error scenario.

**Comment by steveisok** [comment]
@EgorBo @akoeplinger Do you recall how perms are set?

**Comment by EgorBo** [comment]
> @EgorBo @akoeplinger Do you recall how perms are set?

Not sure I follow, 
We require read/write access to the external storage (https://github.com/dotnet/runtime/blob/master/tools-local/tasks/mobile.tasks/AndroidAppBuilder/Templates/AndroidManifest.xml#L8-L9) in order to be able to save the test results there.

**Comment by akoeplinger** [comment]
I think I saw Android 30 returning a path that is inaccessible to adb pull, which Android version are you using?

Ideally we'd find some path or other way to get a location that can be consistently accessed by adb, we don't really care where that is :)

**Comment by mattleibow** [comment]
@akoeplinger yup, API 30.

Can we not pull files using the `run-as` feature of adb? Maybe you can copy the files into a "safe" location and then pull it?

**Comment by mattleibow** [comment]
I see this works for me:

```csharp
#pragma warning disable CS0618 // Type or member is obsolete
var root = Platform.HasApiLevel(30)
    ? Android.OS.Environment.ExternalStorageDirectory.AbsolutePath
    : Application.Context.GetExternalFilesDir(null)?.AbsolutePath ?? FileSystem.AppDataDirectory;
#pragma warning restore CS0618 // Type or member is obsolete

var docsDir = Path.Combine(root, "Documents");

if (!Directory.Exists(docsDir))
    Directory.CreateDirectory(docsDir);

resultsPath = Path.Combine(docsDir, resultsFileName);
```

**Comment by akoeplinger** [comment]
I tried with `run-as` and it didn't work for me. The ExternalStorageDirectory property you're using seems to be deprecated as of API-29: https://developer.android.com/reference/android/os/Environment#getExternalStorageDirectory()

**Comment by akoeplinger** [comment]
We're using the `Context.getExternalFilesDir()` API in dotnet/runtime, can you try whether that one works on API-30?

**Comment by mattleibow** [comment]
It works from inside the app, but then adb has an error. That is why I have the condition in that snippet.

And yes, it is deprecated, but works :)

**Comment by mattleibow** [comment]
I figured out why things might have worked. I was building for 29 so I got those feature sets. If I target 30, then it blows up.

**Comment by mattleibow** [comment]
If I use the internal directory, I get this error:

```
dbug: Executing command: 'C:\Users\matthew\.dotnet\tools\.store\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21111.1\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21111.1\runtimes\any\native\adb\windows\adb.exe -s emulator-5554 pull /storage/emulated/0/Android/data/com.mono.skiasharp.tests/files/Documents/TestResults.xml C:\Users\matthew\AppData\Local\Temp\2iwi01dj.yff'
fail: Hit error (typically permissions) trying to pull /storage/emulated/0/Android/data/com.mono.skiasharp.tests/files/Documents/TestResults.xml
      System.Exception: Failed pulling files: Exit code: 1
      Standard Output:
      adb: error: failed to stat remote object '/storage/emulated/0/Android/data/com.mono.skiasharp.tests/files/Documents/TestResults.xml': Permission denied


         at Microsoft.DotNet.XHarness.Android.AdbRunner.PullFiles(String devicePath, String localPath) in /_/src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs:line 315
         at Microsoft.DotNet.XHarness.CLI.Commands.Android.AndroidRunCommand.InvokeHelper(ILogger logger, String apkPackageName, String instrumentationName, Dictionary`2 instrumentationArguments, String outputDirectory, String deviceOutputFolder, TimeSpan timeout, Int32 expectedExitCode, AdbRunner runner) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidRunCommand.cs:line 120
```

**Comment by mattleibow** [comment]
When I do `run-as` on my API 30 emulator, it takes me to `/data/user/0/com.mono.skiasharp.tests/files/`. I can write to there in my app,  but then xharness can't pull it.

**Comment by greenEkatherine** [comment]
Access permissions to external storage were changed in Android 11 https://developer.android.com/about/versions/11/privacy/storage. When the app targets API 30 we cannot access app's directory outside the app. I will try approach for shared file and see if it helps

**Comment by dellis1972** [comment]
We had to completely rework the Xamarin.Android fast deployment system to work with API 30 and to work around this. 
The external directory is not available. Instead of `context.GetExternalFilesDir()` you can use `context.GetFilesDir()`. This should return a path like `/data/user/0/<packageName>`. And you should be able to write files there. 

You can then use `adb shell run-as <packageName> ls` to view the files in that `internal` directory. `adb pull` and `adb push` will not work with that internal directory. So you need to have a different method to pull the data off (if you need to). 
You might be able to use commands like `adb shell run-as  <packageName> cat foo.log` to pull off a log file and echo that data to the console. Then redirect it to a local file. Alternatively you should be able to copy data to `/data/local/tmp/` and then `adb pull` that off as well. 

One of the issues is not all devices support `run-as`. We found that things under Api 21 do not work. Also the app needs to have the `adroid:debugger=`true` attribute in the application element of the manifest to get it t work. Otherwise you get a `permission denied` error when using `run-as`. 

Please feel free to reach out if you have questions :)

**Comment by greenEkatherine** [comment]
@dellis1972 thanks a lot, this is a very useful information!
@akoeplinger @mattleibow will it work for us to target only API >=21 and add this `android:debugger=true` flag?

**Comment by mattleibow** [comment]
I believe that attribute is defined in the androidmanifest.xml of the app and by default release builds do not have it...

However it may be fine if we have some sort of restrictions.

We could even have a pre-30 path that does the old logic and a 30+ that has these new restrictions. That way we can still keep whatever the rest of the consumers have working

**Comment by akoeplinger** [comment]
It looks like API-31 relaxed this again, I'm seeing no errors pulling from API-31 and API-32 emulators anymore.

**Comment by mattleibow** [comment]
So basically, API 30 is the real pain here? 😄

**Comment by akoeplinger** [comment]
While working on https://github.com/dotnet/xharness/pull/811 I noticed that the PR build hits a queue with API 30 **devices** on it and `adb pull` seems to work fine there which leads me to believe this is only an issue on emulators (or at least some OEMs fixed it in their builds).

**Comment by premun** [comment]
@akoeplinger the Android device queue has both 29 and 30. We were adding devices in 2 batches and the second came already with a newer Android:
https://github.com/dotnet/core-eng/wiki/Mobile-devices-for-.NET-testing#android-testing-queues-overview

**Comment by akoeplinger** [comment]
@premun yup that's fine, it looks like for some reason this doesn't affect devices or at least not the devices we have there even without #811.

**Comment by akoeplinger** [comment]
Another thing I found out is that while pulling files from `context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS)` does work again in API 31+ it still fails there if you try to pull from `context.getCacheDir()`.

What we settled for in dotnet/runtime is to use `context.getCacheDir()` for API 30 (which will use the fallback in #811 via copying to temp) and stick to `context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS)` for all other API levels. That way we only execute the fallback where necessary.

We can reevaluate if we find that causes problems on some other API levels or specific devices in the future but for now I think there's nothing left to do here, closing :)

**Comment by dellis1972** [comment]
Just a heads up according to the docs  https://developer.android.com/training/data-storage/app-specific#external-access-files for `context.getExternalFilesDir`

```
Note: On Android 11 (API level 30) and higher, apps cannot create their own app-specific directory on external storage.
```

not sure if this effects #811

**Comment by akoeplinger** [comment]
@dellis1972 as far as I understand this just means that apps can't create arbitrary paths on external storage and the path you get from `getExternalFilesDir()` includes the package name like `/storage/emulated/0/Android/data/<package name>/files/`

I tested it on API 30, 31 and 32beta without issues so far.
