### ISSUE TITLE
Add UWP support

### ISSUE THREAD

**Issue by mattleibow** [dotnet/xharness#387]
This is very useful to have as they do form about 20% of mobile apps.

**Comment by premun** [comment]
Where did we land with this? Can XHarness be useful for these scenarios or is going without it easier?

**Comment by mattleibow** [comment]
I think PM has to make the decisions on where to focus. I think Android and iOS and WASM was the priority. 

However, there is benefit in this because we sometimes have to make use of "device" functionality - such getting app info and permissions. Even if this is a "slim" part of xharness, it would be great if it could install and start the app and then somehow communicate test results back. The main issue is the setup and teardown of the app - it is a bit annoying to hack around with scripts and things.

**Comment by premun** [comment]
Yeah, thanks for the idea! I don't know anything about how these apps are installed/run but if it comes to this, I think XHarness might be a good place the code in in my opinion.

**Comment by premun** [comment]
No plans to do this
