### ISSUE TITLE
Add a way to exclude tests

### ISSUE THREAD

**Issue by mattleibow** [dotnet/xharness#390]
I have a large test app, and some of the tests require human intervention. This means that we cannot run them on CI and need to be excluded.

**Comment by mattleibow** [comment]
I see this is in the AndroidApplicationEntryPoint.GetTestRunner.

Hopefully once we get #383 then I won't even have to ask this question. 😉

**Comment by premun** [comment]
@mattleibow we support something like this with the `--method` and `--class` parameters. We do not support excluding, but including only like this. Not sure it is enough but we can easily improve that, yeah.

**Comment by radical** [comment]
Traits is another way to do it. Eg. `[Trait("Category","SkipCI")]`, and then `-notrait category=skipci`

**Comment by mattleibow** [comment]
How do I translate that from the cli to the Android instrumentation? Is there some magic for that?

**Comment by mattleibow** [comment]
This is my code: https://github.com/xamarin/Essentials/pull/1558

**Comment by mattleibow** [comment]
I don't see a notrait, just class and method

https://github.com/dotnet/xharness/blob/master/src/Microsoft.DotNet.XHarness.CLI/CommandArguments/TestCommandArguments.cs#L29-L43

**Comment by radical** [comment]
You would need to pass that to the test runner as command line args, or as filters. I'm not familiar with android side of things here, so, I'm not sure how that might be done.

**Comment by mattleibow** [comment]
This does not appear to do anything. Looking at the code it seems not to be connected to anything? The skip part?

```csharp
class TestsEntryPoint : AndroidApplicationEntryPoint
{
    protected override TestRunner GetTestRunner(LogWriter logWriter)
    {
        var testRunner = base.GetTestRunner(logWriter);

        var traits = new[]
        {
            $"{Traits.DeviceType}={Traits.DeviceTypes.ToExclude}",
            $"{Traits.Hardware.Accelerometer}={Traits.FeatureSupport.ToExclude(HardwareSupport.HasAccelerometer)}",
            $"{Traits.Hardware.Compass}={Traits.FeatureSupport.ToExclude(HardwareSupport.HasCompass)}",
            $"{Traits.Hardware.Gyroscope}={Traits.FeatureSupport.ToExclude(HardwareSupport.HasGyroscope)}",
            $"{Traits.Hardware.Magnetometer}={Traits.FeatureSupport.ToExclude(HardwareSupport.HasMagnetometer)}",
            $"{Traits.Hardware.Battery}={Traits.FeatureSupport.ToExclude(HardwareSupport.HasBattery)}",
            $"{Traits.Hardware.Flash}={Traits.FeatureSupport.ToExclude(HardwareSupport.HasFlash)}",
        };

        testRunner.SkipCategories(traits);

        return testRunner;
    }
}
```

**Comment by mattleibow** [comment]
Closing this because it works, just a bit of setup. Thanks for the comments.

**Comment by premun** [comment]
I think Android is not forwarding the arguments after `--` at the moment but this could be easily changed

https://github.com/dotnet/xharness/blob/322e7021377d57258e742c2641f77244a09627b1/src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs#L53

(the `false` there says it doesn't accept the `--` notation and then it would have to be forwarded wherever inside of the command)
