### ISSUE TITLE
Rename the ios command to respect tvOS/watchOS

### ISSUE THREAD

**Issue by premun** [dotnet/xharness#400]
## Context
Currently, everything from issue labels to namespaces (`Microsoft.DotNet.XHarness.iOS`) in code to commands is either `Android` or `iOS`:
```
xharness android test
xharness ios test
...
```

For tvOS, we also use the `ios` command which is a bit confusing:
```
xharness ios test --targets=tvos-simulator ...
```

## Solution 1: Dedicated commands
There is a proposal to introduce new commands (basically aliases) and it's time to decide how we want to do approach this.
We could have:
```
xharness tvos test ...
```

But this command **still needs to accept targets** because we need to be able to target the right version of tvOS and a real device vs. simulator (e.g. `tvos-simulator_13.5`).

Another issue is with the `state` command. Currently, the `state` command returns all of the Apple devices and simulators it detects. We would have to think about whether we want `tvos state` only but this would also complicate things a little bit.

## Solution 2: Umbrella command for everything Apple
Second solution would be to introduce some new keyword that would cover all iOS/tvOS/WatchOS systems and replace the `ios` keyword with this, e.g.:
```
xharness apple test --targets=tvos-simulator ...
xharness apple state
```

Here we would need to decide what the keyword will be..
- `apple`
- `apple-os`
- ...

Please share your opinion about this!

**Comment by premun** [comment]
I am personally for **Solution 2** and the `apple` keyword, not holding a strong opinion on the keyword itself.

**Comment by greenEkatherine** [comment]
I'm also for the second option

**Comment by tkapin** [comment]
Ok, I agree with the proposal of the unified keyword, I'd recommend "appleos" though as it matches the "ios", "tvos" etc. naming and makes clear that it's the apple OSes we are trying to unify.

**Comment by akoeplinger** [comment]
I agree with solution 2 but I think it should be `apple` and not `appleos`, there's no unified apple "OS" so we'd be inventing this concept.

**Comment by premun** [comment]
Re-opening to track Arcade/runtime changes
