### ISSUE TITLE
Rename the default branch name to "main"

### ISSUE THREAD

**Issue by tkapin** [dotnet/xharness#415]
We have decided to unify the naming of our default branches to `main` as all new repos will already use this naming. We are using [GitHub’s new tooling](https://github.com/github/renaming) to make sure branch policies and PRs are automatically updated.

The goal of this issue is to rename the default branch to `main` in this repository by following the renaming guide at <https://aka.ms/m2m-dotnet>.

**Comment by premun** [comment]
Migrated internal pipeline succeeded here: https://dev.azure.com/dnceng/internal/_build/results?buildId=950224&view=results
The latest change produced a package here: https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet-eng&package=Microsoft.DotNet.XHarness.CLI&protocolType=NuGet&version=1.0.0-prerelease.21064.3&view=overview

This means the migration went as expected. Closing this
