### ISSUE TITLE
Add Support for Mac Catalyst 

### ISSUE THREAD

**Issue by steveisok** [dotnet/xharness#435]
We are in the process of building a mac catalyst runtime.  In order to run tests against it, I would like xharness to support running catalyst apps in order to take advantage of the underlying infrastructure.  

- [ ] Add new iOS target (`maccatalyst` would be on suggestion)
- [ ] Launch MacCatalyst app
  - [ ] Support the `test` command
  - [X] Support the `run` command (#462)
- [X] Collect MacCatalyst system logs (#459)

**Comment by tkapin** [comment]
@steveisok - could you please clarify the priority and when do you need it (assuming sooner is better, but it's unclear if its a blocker for you at the moment). @premun is supposed to be on FR for two weeks now, but we can reschedule it if needed.

**Comment by steveisok** [comment]
It's not a blocker, but sooner definitely is better.  I certainly understand if you want to keep Premek on FR.

**Comment by rolfbjarne** [comment]
> * Wire up correctly to mlaunch in order to launch a catalyst app

You don't need mlaunch to launch Mac Catalyst apps, they're launched like macOS apps (so just call Process.Start on the executable, or whatever xharness does for macOS apps).

**Comment by premun** [comment]
@rolfbjarne do you know if there is some MacCatalyst system log like we have for the simulators? I was trying to find how you handle this in `xamarin-macios` but couldn't see it

**Comment by rolfbjarne** [comment]
@premun there's no Mac Catalyst-specific system log like there are for simulators, it would be the normal macOS system-level log.

**Comment by rolfbjarne** [comment]
and that's not captured in xharness, so if you want it you'd have to add support for it

**Comment by premun** [comment]
Right, thanks!

I logged an issue #459 and will revisit it later so that we don't have to wait for this now.
