### ISSUE TITLE
[Nugets] Allow the usage of xcode specific branches for xharness to be consumed during betas

### ISSUE THREAD

**Issue by mandel-macaque** [dotnet/xharness#441]
Apple is not consistent with the different simulators that are supported, or in general, Apple does not guarantee to be consistent with everything. This results in xcode versions that can change behaviour that is expected by xharness, one of those examples is https://github.com/xamarin/xamarin-macios/issues/10593 in which the min watchOS simulator supported has changed. 

Ideally we need to ensure that we have nugets in the previews that contain the branch to identify the build branch. At the moment, in xamarin-macios we use the xcode version:

* xcode12.3
* xcode12.4
* xcode11

And so on. Is important to note that there is no 11.0 but 11.

**Comment by premun** [comment]
@mandel-macaque I will set up an example branch next week. What's the first one I can go? 12.5?

**Comment by premun** [comment]
Also - do we want Maestro to open PRs for merging main to xcode branches?

**Comment by premun** [comment]
This was implemented (#451 #450 https://github.com/dotnet/versions/pull/678). I created 2 follow-ups (#452 #453) that will improve our workflow
