### ISSUE TITLE
Add ability to provide screenshots on test failure

### ISSUE THREAD

**Issue by greenEkatherine** [dotnet/xharness#444]
@PureWeen:
> In our device tests we do color testing and things of that nature
> So if something is failing on CI (around color testing) a lot of times it's useful to see what something was supposed to render as but didn't

**Comment by greenEkatherine** [comment]
@PureWeen could you please provide more details to understand the motivation of this task? i.e. for which tests is it required, how often you need to investigate them?

**Comment by premun** [comment]
I don't think we have enough specs here. We can open a new one if this becomes hot again.
