### ISSUE TITLE
Detect exit code when calling `apple run` for MacCatalyst target 

### ISSUE THREAD

**Issue by premun** [dotnet/xharness#462]
1. It seems MacCatalyst doesn't forward the exit code of the app
2. We cannot get the system logs yet (#459) so we cannot get the exit code from there neither

We should investigate 1. or wait for 2.

**Comment by akoeplinger** [comment]
@premun can you please try to run the binary in the `HelloCatalyst.app/Contents/MacOS` folder directly and see whether you get the exit code that way?

**Comment by premun** [comment]
@akoeplinger will try!

Meanwhile, I was able to get it from the `/var/log/system.log` the same way I get it from Simulators btw

**Comment by premun** [comment]
Ah, cool, running the binary works! Also gets us the logs!
