### ISSUE TITLE
Add option to check for wifi (ip address) on Android

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/xharness#476]
In https://github.com/dotnet/core-eng/issues/11891 we hit an issue where for some reason the WiFi was disabled on the Android phones which meant it didn't have an IP and couldn't reach the Internet which caused some DNS tests to fail.

We should have a way to detect this and fail with some distinct exit code so this can be bubbled up and be reported as an infrastructure failure on Helix.

I think we'll need to add this behind an opt-in/opt-out option since there could be valid use cases where you do not want this check (e.g. testing something in Airplane mode). My preference would be opt-in so we could only set this when running on Helix.

/cc @MattGal

**Comment by greenEkatherine** [comment]
Raise pull request https://github.com/dotnet/xharness/pull/547
New parameter `--wifi` introduced:
- `--wifi [enable]` - switching wifi on
- `--wifi disable` - switching wifif off
- without this parameter no additional checks are providing as before
