### ISSUE TITLE
xharness should also download/install the versions of the simulators

### ISSUE THREAD

**Issue by mattleibow** [dotnet/xharness#478]
It would be nice if there was a way to install simulators for iOS as all the info to the URL is there:

https://github.com/xamarin/xamarin-macios/tree/main/tools/siminstaller

I would maybe do something like:

```
xharness apple simulators install ios-simulator-64_10.3.1
```

When doing this for Android, it sort of fits in with #380 and #393 but this just calls upon the sdkmanager to also download.

**Comment by premun** [comment]
There is some code for this in this repo already which is packaged into another .NET tool and can do this:
- https://github.com/dotnet/xharness/tree/main/tools/Microsoft.DotNet.XHarness.SimulatorInstaller
- https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet-eng&package=Microsoft.DotNet.XHarness.SimulatorInstaller&protocolType=NuGet&version=1.0.0-prerelease.21124.1

This tool is actually originally coming from the siminstaller you've linked, just it was re-written.

We could easily move these commands into XHarness CLI itself. @tkapin thoughts?
