### ISSUE TITLE
If Xcode path is not provided, use the xcode path from xcode-select

### ISSUE THREAD

**Issue by mandel-macaque** [dotnet/xharness#49]
If the user does not provide the xcode path, use the path returned by xcode-select.

That means that we have to set the path to be lazy and change the mono options definition from using a '=' to a ':' so that it is an optional parameter.

**Comment by premun** [comment]
So this happens here already:
https://github.com/dotnet/xharness/blob/3b84a4154b6491ccebc2c0a502ec12411990e843/src/Microsoft.DotNet.XHarness.iOS.Shared/Execution/ProcessManager.cs#L442-L466

**Comment by premun** [comment]
I think this is resolved now. Works as expected.
