### ISSUE TITLE
Support passing environment variables to iOS apps launched by xharness, and support separate install, run-test, and uninstall subcommands

### ISSUE THREAD

**Issue by imhameed** [dotnet/xharness#493]
I'm working on getting CoreCLR's runtime tests working with Mono on iOS devices. In https://github.com/dotnet/runtime/pull/43954, I'm bundling multiple runtime test assemblies (with one entry point each) together into a single iOS app bundle, similar to what we currently do on Android. I'm passing the entry point assembly to run through an environment variable (unlike Android, which uses a command line argument): https://github.com/dotnet/runtime/pull/43954/files#diff-6cef647106df3b37e45599e150f97a7dc3678f2606723b1967dbda7d1f0a42b9R268-R273

I've verified that doing this works locally when launching runtime test assemblies (via their containing iOS app bundle) via mlaunch. To make this run for real on CI I'll need to do this with xharness.

xharness doesn't appear to have a way to add passthrough environment variables, although it does appear to support mlaunch's `--setenv` option internally:
https://github.com/dotnet/xharness/blob/main/src/Microsoft.DotNet.XHarness.iOS.Shared/Execution/Arguments.cs#L199-L222

There was also a request in https://github.com/dotnet/xharness/issues/397 to add separate install, run-test, and uninstall commands to xharness for Android. That will also be necessary for iOS, because a single iOS runtime test app bundle will contain multiple entry points.

**Comment by premun** [comment]
@imhameed sure, this should be a piece of cake!

Are env variables fine or do you need to pass arguments to the app directly as well (we support this already but not sure it works on the mlaunch side)?

**Comment by premun** [comment]
@imhameed can you also please provide me with a test application and some instructions on how you would like to run the tests using it so that I have a good picture of things should work?

**Comment by imhameed** [comment]
> @imhameed sure, this should be a piece of cake!

Great!

> I have some questions:
> 
> 1. Are env variables fine or do you need to pass arguments to the app directly as well (we support this already but not sure it works on the mlaunch side)?
> 
> 2. For the `run-test`, `install`/`uninstall` flows, I can follow the flow from Android?
> 
> 3. I know that for Simulators there's no install/uninstall, we just run the app so we won't need to get the device ID but I need to look into whether we can just run the app without having to have to copy it there repeatedly. I imagine we might keep the same flow for device/Simulator though so that it's not confusing where in/uninstall will be a no-op

1. I don't need to pass arguments to the app right now. And I think mlaunch does support this.
2. Yes.
3. Sounds fine; the goal is to avoid burning time on redundant data transfer/install/verification work.


> @imhameed can you also please provide me with a test application and some instructions on how you would like to run the tests using it so that I have a good picture of things should work?

Sure. I don't have one handy right now but I'll send you something shortly.

**Comment by premun** [comment]
@imhameed I opened a pull request (#496) for the first part where we also set the environmental variables.
(please note that these were passed as regular arguments already before)

**Comment by premun** [comment]
Variables are not passed (https://github.com/dotnet/xharness/pull/521#issuecomment-807365536)

**Comment by premun** [comment]
Blocked, waiting for new mlaunch

**Comment by premun** [comment]
@imhameed you can use XHarness **1.0.0-prerelease.21220.1** and newer to control how the app is installed used and uninstalled.

I noticed one thing using the app you've sent me - the app should run the test and quit so that things work well.

The commands that you want to use:
```
xharness apple install ...
xharness apple just-run ...
xharness apple just-run ...
xharness apple just-run ...
xharness apple uninstall ...
```

This will be faster as it won't reinstall the app at each run. This will then immensely speed up scenarios with real devices where these operations take more time.

Please note that `uninstall` accepts the the `app` arg too but it should be the bundle id rather than path to the app package.

**Comment by premun** [comment]
Closing as it is now implemented.
