### ISSUE TITLE
XHarness iOS simulator is not removed

### ISSUE THREAD

**Issue by mattleibow** [dotnet/xharness#507]
I think the simulator that xharness creates is never actually deleted. I noticed this locally and I think also that CI had a bad sim that got stuck somewhere. Now it never re-creates the sim and stays stuck.

There doesn't seem to be logic to remove the sim after the tests, or a command to explicitly delete them.

**Comment by premun** [comment]
We had a call with Matthew and figured out that the best way to approach this would be to add a new option to XHarness that would make sure the simulator data get erased at the end of the run.

This option would call `xcrun simctl` and use some of the command such as `shutdown`, `erase` and `delete`. It is up to an investigation which commands will remove the right data.
