### ISSUE TITLE
xamarin-macios regression - test targets are skipped 

### ISSUE THREAD

**Issue by mandel-macaque** [dotnet/xharness#514]
There has been a change in the shared library that has had a regression making the xamarin-macios to be skipped when they required iOS simulators. We have been able to find the exact version that introduced the regression:

* 1.0.0-prerelease.21109.1 - Last working version
* 1.0.0-prerelease.21111.1 - Version when the issues appear.

**Comment by premun** [comment]
21111.1 is a README change, 21109.1 is this:
https://github.com/dotnet/xharness/commit/66b9a52dfea930ff2cfb588e5f2636932a1f6868

**Comment by premun** [comment]
I think this is long fixed since we have bumped many times since then
