### ISSUE TITLE
Support passing environment variables to Android apps

### ISSUE THREAD

**Issue by greenEkatherine** [dotnet/xharness#525]
Set environment variables for Android apps the same way as it was done for Apple https://github.com/dotnet/xharness/pull/496

Initial request https://github.com/dotnet/core-eng/issues/12058#issuecomment-806042545

**Comment by premun** [comment]
Please verify you can read the variables in the app

**Comment by greenEkatherine** [comment]
It is not possible to pass environment variables to Android app. App runs not in a child process of `adb shell` so environment variables provided there are not visible for the app. I may suggest next workarounds:

- These variables still might be passed as `--arg` if they only needed inside the app as some parameters - it is already implemented
- Introduce new parameter or format for environment variables but it would be **_client's responsibility_** to set them as  environment variables inside the test app.

Some thoughts about the second option: I would like to use runtime approach as an example https://github.com/dotnet/runtime/pull/44644 - pass environment variables in `--args` with some prefix. It would differ from `--setenv` for `xharness apple` but we actually don't set a variable in that case because client would need to do it. 

@billwert what would work for you?

**Comment by billwert** [comment]
Hi @greenEkatherine!

Using `-e` from `adb` to set values as the runtime approach shown is probably fine. @CoffeeFlux can you confirm this will happen early enough in the process for our purposes?

**Comment by CoffeeFlux** [comment]
@billwert I think that should work, since it seems like we're using it for `MONO_LOG_LEVEL` (which we also read in fairly early).

**Comment by greenEkatherine** [comment]
great, in that case you may just reuse the same approach as for `MONO_LOG_LEVEL`. I will add this point into documentation. Is there anything else what I can do for this issue?

**Comment by greenEkatherine** [comment]
@billwert please confirm if I may close it now

**Comment by greenEkatherine** [comment]
Confirmed offline with Bill that it can be closed now
