### ISSUE TITLE
Xunit should respect `[ActiveIssue]` attribute

### ISSUE THREAD

**Issue by EgorBo** [dotnet/xharness#53]
We don't use "rsp/ignore list" approach in `dotnet/runtime` anymore, thus `xharness` needs to support
`[ActiveIssue]`, e.g. https://github.com/dotnet/runtime/blob/110282c71b3f7e1f91ea339953f4a0eba362a62c/src/libraries/System.ComponentModel.Composition/tests/System/Integration/CompositionContainerAttributedModelCycleTests.cs#L33

we've marked several hundreds of `dotnet/runtime` tests with it.

https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.XUnitExtensions/src/Discoverers/ActiveIssueDiscoverer.cs

**Comment by EgorBo** [comment]
Turns out there are ~2000 ActiveIssues (half of them for mono) so we can't run the tests until this issue if fixed.

**Comment by premun** [comment]
Apparently this didn't work and the tests are still being executed

**Comment by premun** [comment]
Ok, the issue was - there was a misunderstanding and a **category** named like that was ignored, not the attribute

**Comment by marek-safar** [comment]
@premun @mandel-macaque is there any ETA when this will be resolved?

**Comment by premun** [comment]
@mandel-macaque I will take this and do it today

**Comment by premun** [comment]
@mandel-macaque is taking over this after all. ETA hopefully today, Manuel?
