### ISSUE TITLE
Android device is not authorized

### ISSUE THREAD

**Issue by premun** [dotnet/xharness#549]
Happened in the Arcade CI:
```
[10:33:06] fail: Error trying to get device: error: device unauthorized.
                 This adb server's $ADB_VENDOR_KEYS is not set
                 Try 'adb kill-server' if that seems wrong.
                 Otherwise check for a confirmation dialog on your device.
```

Full logs:
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-arcade-refs-pull-7237-merge-b9b094f6acca4bb5b6/System.Buffers.Tests-arm64-v8a/console.0ce4f811.log?sv=2019-07-07&se=2021-05-04T17%3A30%3A42Z&sr=c&sp=rl&sig=mTRbeg%2FHeHikjallXBr9u4%2BDAiGLQaOYCRMM%2B0VwK4w%3D

Build:
https://dev.azure.com/dnceng/public/_build/results?buildId=1088447&view=logs&jobId=93dcc217-cd96-5c51-d4a3-227cae99938a&j=5fae9d80-faa2-578a-a809-a74b747965c3&t=97151e8a-23a0-5bc9-6f66-0b9b4de62b72&s=ee3800fd-6e81-525f-e564-94108585217d

**Comment by greenEkatherine** [comment]
The latest occurrence https://dev.azure.com/dnceng/public/_build/results?buildId=1126311&view=logs&j=21143b0a-ace1-5058-215e-b11404388d17&s=ee3800fd-6e81-525f-e564-94108585217d&t=b6047ca6-0230-5e90-2195-54379d550513&l=31

**Comment by greenEkatherine** [comment]
Query to find all these failures:
```
WorkItems
| where ExitCode == 71
| where QueueName == "windows.10.amd64.android.open"
| where FriendlyName == "System.Buffers.Tests-arm64-v8a"
```

**Comment by ilyas1974** [comment]
I talked with @parose1 and he is going to check the above systems and validate the that the systems are set up correctly.

**Comment by parose1** [comment]
Hello, I connected to DNCENGWIN-057, 111, and 113 and was able to run adb commands and did not get any authorization issues. When I created the MLS ticket to have them enable USB debugging I asked that "Always allow from this computer" was selected. Are you still getting authorization issues on these machines?

![image](https://user-images.githubusercontent.com/48035740/118045438-bfa31100-b32c-11eb-9a6a-dae69b2a465a.png)

**Comment by greenEkatherine** [comment]
@parose1 thank you for confirmation, yes, it's ok now. It seems that issue was mitigated after some time - probably after reboot/update.

> When I created the MLS ticket to have them enable USB debugging I asked that "Always allow from this computer" was selected

Do you know, does this window always prompted? Would it be a good idea to add into this ticket additional check that `adb devices -l` doesn't show some unauthorized device?

**Comment by parose1** [comment]
@greenEkatherine I'm not sure if the "Always allow from this computer" prompt always appears when re-authorizing the phone to the host. I do have MLS run the 'adb devices -l' command to verify before handing back to me. I also reboot the machine and run the adb commands again just to be sure as the device would go back to unauthorized after a reboot if "Always allow from this computer" was not selected.

**Comment by greenEkatherine** [comment]
@parose1 thank you for your help, I think it should be enough from your side. From our side I'm going to raise PR where I will add indication of that state with specific exit code, not just `GENERAL_FAILURE` as it is now
