### ISSUE TITLE
[iOS] Do not generate the human readable html by default.

### ISSUE THREAD

**Issue by mandel-macaque** [dotnet/xharness#55]
The parsing of the xml to a human readable version is done for the xamarin/xamarin-macios team. This does not make any sense in the terms of the xharness tool as a CLI, set it to not be generated by default and let the xamarin/xamarin-macios set it.

**Comment by premun** [comment]
Ah, sorry, I forgot to create this one

**Comment by mandel-macaque** [comment]
@premun I'm on it, no worries :)
