### ISSUE TITLE
Wrap custom user Helix payloads into the Helix SDK job scripts

### ISSUE THREAD

**Issue by premun** [dotnet/xharness#590]
**Context**
The Helix SDK has [wrapper scripts](https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner/xharness-runner.apple.sh) for execution of XHarness payloads that does tricks around user sessions, signing, re/starting of the simulator and so on. The iOS payloads won't work without it. The point of having the Helix SDK is to capture these necessities and make it transparent for the user who doesn't know the specifics of the environment setup.

**Problem**
The newly added commands (`install`, `just-run`, `just-test`, `uninstall`) are supposed to allow the user to drive the execution.
However, when we create a Helix job that lets the user to run their own payload (Helix SDK only pre-installs .NET and XHarness on the Helix machine for the user), the user has to know to also execute the wrapper script somehow. They will fail to execute the job because:
- For devices, the app won't be signed
- For Simulators, the Simulator.app process won't be reachable (requires `launchctl asuser`)
- Clean up actions based on XHarness exit code won't happen (e.g. retry + reboot)

**Goal**
The Helix SDK has to wrap user's payload in the wrapper script mentioned above and execute it in that context. For that, the API has to be most likely changed so that user cannot execute their payload on its own. It is part of this issue to figure out how.

**Comment by premun** [comment]
@imhameed not sure how far you are with running the `install`, `just-run`, `uninstall` commands in Helix, but I realized today that it won't work until the above happens.

**Comment by imhameed** [comment]
Good to know. So far I've been prototyping with `apple run`, so I haven't encountered this yet.

**Comment by premun** [comment]
@imhameed roughly when do you think this will start to block you? The commands work on your local just won't work in Helix. Android commands would work in Helix.

**Comment by premun** [comment]
I just got this work prioritized because I see it will be a blocker for you. I estimate around 4 days of work so it would be ready next week.
