### ISSUE TITLE
Capture stderr and stdout when running iOS apps

### ISSUE THREAD

**Issue by imhameed** [dotnet/xharness#596]
mlaunch has two options that capture stderr/stdout: `--stderr=path/to/outfile.txt` and `--stdout=path/to/outfile.txt`. When I launch a failing test manually using these options, I see a bunch of useful information that I don't see when using `xharness apple run` or `xharness apple just-run`, even when using maximum xharness verbosity.

An example:

```
mkdir out
```

Here's an xharness apple run command:
```
imhameed@ms-ih-mbp ~/ms/dnr-9.x-ios/runtime/artifacts/tests/coreclr/iOSSimulator.x64.Release/JIT/SIMD$ xharness.sh apple run --app=JIT_SIMD.app --output-directory=out --targets ios-simulator-64 --mlaunch=/Users/imhameed/ms/xharness/artifacts/tmp/Debug/macios-binaries/mlaunch/bin/mlaunch --set-env=MONO_APPLE_APP_ENTRY_POINT_LIB_NAME=VectorCopyToArray_r.dll --expected-exit-code=100 
XHarness command issued: apple run --app=JIT_SIMD.app --output-directory=out --targets ios-simulator-64 --mlaunch=/Users/imhameed/ms/xharness/artifacts/tmp/Debug/macios-binaries/mlaunch/bin/mlaunch --set-env=MONO_APPLE_APP_ENTRY_POINT_LIB_NAME=VectorCopyToArray_r.dll --expected-exit-code=100
info: Preparing run for ios-simulator-64
info: Getting app bundle information from '/Users/imhameed/ms/dnr-9.x-ios/runtime/artifacts/tests/coreclr/iOSSimulator.x64.Release/JIT/SIMD/JIT_SIMD.app'
info: Looking for available ios-simulator-64 simulators..
info: Found simulator device 'iPhone X (iOS 14.4) - created by XHarness'
info: Installing application 'JIT_SIMD' on 'iPhone X (iOS 14.4) - created by XHarness'
info: Application 'JIT_SIMD' was installed successfully on 'iPhone X (iOS 14.4) - created by XHarness'
info: Starting application 'JIT_SIMD' on 'iPhone X (iOS 14.4) - created by XHarness'
info: App run ended with 1
fail: Application has finished with exit code 1 but 100 was expected
XHarness exit code: 71 (GENERAL_FAILURE)
```

Here's the contents of `out/`:
```
imhameed@ms-ih-mbp ~/ms/dnr-9.x-ios/runtime/artifacts/tests/coreclr/iOSSimulator.x64.Release/JIT/SIMD$ ls out 
iPhone X (iOS 14.4) - created by XHarness.log  list-ios-simulator-64-20210513_083529.log      run-ios-simulator-64.log
```

Here's the contents of `out/iPhone X (iOS 14.4) - created by XHarness.log`:
```
May 13 08:35:35 ms-ih-mbp JIT_SIMD[93037]: assertion failed: 19H512 18D46: libxpc.dylib + 50260 [26B6416F-496E-32F6-AC9D-FFCD86331B43]: 0x7d
May 13 08:35:35 ms-ih-mbp com.apple.CoreSimulator.SimDevice.941235AB-7563-4D79-AC28-946B7AD2304A[47205] (UIKitApplication:net.dot.JIT_SIMD[fed2][rb-legacy][93037]): Service exited with abnormal code: 1
```

Here's the contents of `out/list-ios-simulator-64-20210513_083529.log`:
https://gist.github.com/imhameed/cb7da703b010b3e876c049f5eca8cde9#file-list-ios-simulator-64-20210513_083529-log

And the contents of `out/run-ios-simulator-64.log`:
https://gist.github.com/imhameed/cb7da703b010b3e876c049f5eca8cde9#file-run-ios-simulator-64-log

Now, here's the mlaunch command I'm running: 
```
imhameed@ms-ih-mbp ~/ms/dnr-9.x-ios/runtime/artifacts/tests/coreclr/iOSSimulator.x64.Release/JIT/SIMD$ /Users/imhameed/ms/xharness/artifacts/tmp/Debug/macios-binaries/mlaunch/bin/mlaunch --sdkroot /Applications/Xcode.app -setenv=MONO_APPLE_APP_ENTRY_POINT_LIB_NAME=VectorCopyToArray_r.dll --device=:v2:udid=941235AB-7563-4D79-AC28-946B7AD2304A --launchsimbundleid=net.dot.JIT_SIMD --stderr=out/stderr.txt --stdout=out/stdout.txt
Press enter to terminate the application
>Press enter to terminate the application
>%
imhameed@ms-ih-mbp ~/ms/dnr-9.x-ios/runtime/artifacts/tests/coreclr/iOSSimulator.x64.Release/JIT/SIMD$ echo $?
0
```

`out/stdout.txt` is empty. But `out/stderr.txt` has a bunch of useful information that goes a long way towards helping me diagnose the underlying issue:
```
2021-05-13 08:41:17.230454-0400 JIT_SIMD[93124:27637812] assembly_preload_hook: System.Private.CoreLib (null) /Users/imhameed/Library/Developer/CoreSimulator/Devices/941235AB-7563-4D79-AC28-946B7AD2304A/data/Containers/Bundle/Application/BF0F0EF3-2C95-456C-BD0B-8E5EA3F7D247/JIT_SIMD.app
2021-05-13 08:41:17.287877-0400 JIT_SIMD[93124:27637812] assembly_preload_hook: VectorCopyToArray_r.dll (null) /Users/imhameed/Library/Developer/CoreSimulator/Devices/941235AB-7563-4D79-AC28-946B7AD2304A/data/Containers/Bundle/Application/BF0F0EF3-2C95-456C-BD0B-8E5EA3F7D247/JIT_SIMD.app
2021-05-13 08:41:17.289413-0400 JIT_SIMD[93124:27637812] Executable: VectorCopyToArray_r.dll
2021-05-13 08:41:17.289541-0400 JIT_SIMD[93124:27637812] assembly_preload_hook: System.Runtime  /Users/imhameed/Library/Developer/CoreSimulator/Devices/941235AB-7563-4D79-AC28-946B7AD2304A/data/Containers/Bundle/Application/BF0F0EF3-2C95-456C-BD0B-8E5EA3F7D247/JIT_SIMD.app
2021-05-13 08:41:17.296120-0400 JIT_SIMD[93124:27637812] assembly_preload_hook: System.Numerics.Vectors  /Users/imhameed/Library/Developer/CoreSimulator/Devices/941235AB-7563-4D79-AC28-946B7AD2304A/data/Containers/Bundle/Application/BF0F0EF3-2C95-456C-BD0B-8E5EA3F7D247/JIT_SIMD.app
2021-05-13 08:41:17.298088-0400 JIT_SIMD[93124:27637812] assembly_preload_hook: System.Console  /Users/imhameed/Library/Developer/CoreSimulator/Devices/941235AB-7563-4D79-AC28-946B7AD2304A/data/Containers/Bundle/Application/BF0F0EF3-2C95-456C-BD0B-8E5EA3F7D247/JIT_SIMD.app
Unable to load ICU dat file '/Users/imhameed/Library/Developer/CoreSimulator/Devices/941235AB-7563-4D79-AC28-946B7AD2304A/data/Containers/Bundle/Application/BF0F0EF3-2C95-456C-BD0B-8E5EA3F7D247/JIT_SIMD.app/icudt.dat'.2021-05-13 08:41:17.359092-0400 JIT_SIMD[93124:27637812] ((null) error) * Assertion at /Users/imhameed/ms/dnr-9.x-ios/runtime/src/mono/mono/metadata/exception.c:64, condition `is_ok (error)' not met, function:mono_exception_new_by_name, (null) assembly:/Users/imhameed/Library/Developer/CoreSimulator/Devices/941235AB-7563-4D79-AC28-946B7AD2304A/data/Containers/Bundle/Application/BF0F0EF3-2C95-456C-BD0B-8E5EA3F7D247/JIT_SIMD.app/System.Private.CoreLib.dll type:TypeInitializationException member:(null)
2021-05-13 08:41:17.359238-0400 JIT_SIMD[93124:27637812] Exit code: 1.
```

And for reference, here's the helix log output of this test running (and failing) on dotnet/runtime CI:
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43954-merge-746656068f9c4118bd/JIT/console.8189069e.log?sv=2019-07-07&se=2021-06-01T12%3A51%3A24Z&sr=c&sp=rl&sig=gaybtcLHq%2FegHmiFOQd4Th%2BtCGLnOQmi128qtCSBnXI%3D

It'd be helpful to have all of the above information visible when a test fails.

**Comment by steveisok** [comment]
This is important to have available as we don't have enough information on CI to determine why an app crashed, for example.

**Comment by premun** [comment]
Whatever was going to app's stdout/stderr was piped to the `run-` or `test-` log if I am not wrong. We shouldn't be technically missing anything already, it's just in one of the attached files. But I spoke with Imran and we should pipe it to XHarness' stdout so it gets more visibility. I will double check we have everything that is written down in this issue.

**Comment by imhameed** [comment]
> Whatever was going to app's stdout/stderr was piped to the `run-` or `test-` log if I am not wrong. We shouldn't be technically missing anything already, it's just in one of the attached files.

If you check the attached xharness-generated files for a relevant substring from stdout.txt--like "is_ok (error)"--you'll find that it's missing. And when xharness executes mlaunch, it doesn't pass either `--stderr` or `--stdout`, so that output is lost.

**Comment by imhameed** [comment]
Looks like stdout capture is present when running apps on devices: https://github.com/dotnet/xharness/blob/9596c3fbbb718819bc4bb9a9e3f6271b50fc718a/src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppRunner.cs#L312

stderr is not captured on devices. And neither stdout nor stderr are captured on the simulator.

But yeah, piping all this to xharness's stdout, preferably not interleaved with the rest of xharness's output and clearly demarcated with some easy-to-find header, would be excellent.
