### ISSUE TITLE
Allow customizing the name of the stdout/stderr log files generated by mlaunch

### ISSUE THREAD

**Issue by imhameed** [dotnet/xharness#601]
In https://helix.dot.net/api/jobs/29d28251-7a46-4278-bf6c-a77572d254f0/workitems/JIT.CodeGenBringUpTests?api-version=2019-06-17, there's only one pair of stdout/stderr logs available, despite there being multiple tests contained within this app bundle. Also, the logs are totally empty, even when being `cat`ted immediately after xharness returns.

It'd be helpful to be able to specify some part of the name of the log file by passing another command line argument. Here's how xharness is currently being used for the draft runtime test lane: https://github.com/dotnet/runtime/pull/43954/files#diff-3e5a329159ca5b2268e62be8a0d776b6092681e9b241210cb4d57e3454816abcR395-R402

**Comment by premun** [comment]
@imhameed I am not sure about whether this functionality belongs to XHarness. I would much rather prefer you did 
```sh
mv $output_directory/$bundle_id.log $output_directory/whatever_you_like.log
```
rather than cluttering the CLI with options around file system behavior.

I will talk to my team first about this but I don't think we want to have ~100 lines of C# around this logic.
