### ISSUE TITLE
Add timestamp to the log

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/xharness#610]
I am trying to investigate a test timeout issue. It would be helpful to have timestamps in the log. Right now xharness print logs like this:
```
  Discovering: reflection.SetValue.XUnitWrapper
  Discovered:  reflection.SetValue.XUnitWrapper
  Discovering: reflection.DefaultInterfaceMethods.XUnitWrapper
  Discovered:  reflection.DefaultInterfaceMethods.XUnitWrapper
  Discovering: reflection.Modifiers.XUnitWrapper
  Discovered:  reflection.Modifiers.XUnitWrapper
  Discovering: reflection.StaticInterfaceMembers.XUnitWrapper
  Discovered:  reflection.StaticInterfaceMembers.XUnitWrapper
  Starting:    reflection.StaticInterfaceMembers.XUnitWrapper
```
It would be nice to have logs like this
```
 [yyyy/MM/dd HH:mm:ss.ff] Discovering: reflection.SetValue.XUnitWrapper
 [yyyy/MM/dd HH:mm:ss.ff] Discovered:  reflection.SetValue.XUnitWrapper
 [yyyy/MM/dd HH:mm:ss.ff] Discovering: reflection.DefaultInterfaceMethods.XUnitWrapper
 [yyyy/MM/dd HH:mm:ss.ff] Discovered:  reflection.DefaultInterfaceMethods.XUnitWrapper
 [yyyy/MM/dd HH:mm:ss.ff] Discovering: reflection.Modifiers.XUnitWrapper
 [yyyy/MM/dd HH:mm:ss.ff] Discovered:  reflection.Modifiers.XUnitWrapper
 [yyyy/MM/dd HH:mm:ss.ff] Discovering: reflection.StaticInterfaceMembers.XUnitWrapper
 [yyyy/MM/dd HH:mm:ss.ff] Discovered:  reflection.StaticInterfaceMembers.XUnitWrapper
 [yyyy/MM/dd HH:mm:ss.ff] Starting:    reflection.StaticInterfaceMembers.XUnitWrapper
```

To achieve this, `DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss.ff")` should be added to the following places
https://github.com/dotnet/xharness/blob/b2297d610df1ae15fc7ba8bd8c9bc0a7192aaefa/src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs#L35
https://github.com/dotnet/xharness/blob/b2297d610df1ae15fc7ba8bd8c9bc0a7192aaefa/src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs#L43
https://github.com/dotnet/xharness/blob/b2297d610df1ae15fc7ba8bd8c9bc0a7192aaefa/src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs#L57-L58

**Comment by fanyang-mono** [comment]
@premun  This is one of the log that you could take a look.

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-49662-merge-231998ab087a41dcac/PayloadGroup0/console.d239c696.log?sv=2019-07-07&se=2021-06-13T22%3A51%3A55Z&sr=c&sp=rl&sig=wEFDfBxSxLT2W9ShoHLaz4nlGeIC7JKwVJXreJG5fRE%3D

**Comment by premun** [comment]
We discussed this offline. Nothing we can do as this is not the test runner in question
