### ISSUE TITLE
Throw error on Windows/Linux.

### ISSUE THREAD

**Issue by mandel-macaque** [dotnet/xharness#67]
The ios verb cannot work on Windows, makes no sense. Throw an error when a user tries to execute any of the ios verbs on windows or linux.

**Comment by premun** [comment]
There goes my development experience on Windows 😅

We also shouldn't show it in help on Windows as well.

But maybe we really just should have 2 packages - CLI.iOS and CLI.Android..
No Android users download a large package thanks to mlaunch and then won't be able to use most of it.

**Comment by mandel-macaque** [comment]
@premun that is actually a good point, making the windows users to download mlaunch seems evil.
