### ISSUE TITLE
[iOS] Remove Mono.Options from the TestRunner

### ISSUE THREAD

**Issue by mandel-macaque** [dotnet/xharness#72]
We want to keep the dependencies to the minimum.

**Comment by premun** [comment]
Mono.Options.dll is 45 kB, maybe we want to keep it after all? Doesn't look that bad and we would bring in another code that would have to do the same instead so..

**Comment by premun** [comment]
@mandel I would just close this one? Mono.Options is tiny and dependency-less. The NUnit/xUnit runners are way bigger and this brings value to us actually.

**Comment by akoeplinger** [comment]
Yeah I agree, using Mono.Options sounds fine.
