### ISSUE TITLE
Crash reports are not symbolicated/processed on Simulators

### ISSUE THREAD

**Issue by premun** [dotnet/xharness#849]
It seems we skip some steps [here](https://github.com/dotnet/xharness/blob/2863beb74c1abad7ddfe9ef7afea6fc2605e8a03/src/Microsoft.DotNet.XHarness.iOS.Shared/CrashSnapshotReporter.cs#L98) and the crash reports don't get symbolicated.

Crashing app is here:
https://dev.azure.com/xamarin/public/_build/results?buildId=58903&view=logs&j=84a022bb-4bdc-5585-8146-137444174249&t=d794747c-65a6-5105-c6e6-e1e37436ed3e

Or also here:

1. `git clone https://github.com/dotnet/maui`
2. `dotnet build ./Microsoft.Maui.BuildTasks.slnf`
3 `./build.ps1 -Script eng/devices/ios.cake --project="/Users/ruimarinho/dotnet/maui/src/Controls/tests/DeviceTests/Controls.DeviceTests.csproj" --device=ios-simulator-64--results=TestResultsDirectory --binlog=device_ios.binlog`

**Comment by rolfbjarne** [comment]
Historical reasons why we're just processing crash reports from a device:

1. There's no need to call mlaunch to get the crash report, it's already available on the file system. In other words this code is only applicable for crash reports from a device: https://github.com/dotnet/xharness/blob/2863beb74c1abad7ddfe9ef7afea6fc2605e8a03/src/Microsoft.DotNet.XHarness.iOS.Shared/CrashSnapshotReporter.cs#L153-L162
2. We JIT in the simulator, which means that managed frames won't be symbolicated anyway (this is not entirely true on ARM64 anymore).
