### ISSUE TITLE
[iOS] Issues launching an application on a iOS32 simulator.

### ISSUE THREAD

**Issue by mandel-macaque** [dotnet/xharness#85]
We have an issue when launching applications on a 32b simulator. Although I suspect it will happen the same with a ios 64 sim. The application was compiled using xamarin-macios to test the xharness tool. 

Useful logs:

[iPhone 5.log](https://github.com/dotnet/xharness/files/4532064/iPhone.5.log)

[run-Simulator_iOS32.log](https://github.com/dotnet/xharness/files/4532065/run-Simulator_iOS32.log)

**Comment by premun** [comment]
@mandel-macaque is this issue still happening?

**Comment by mandel-macaque** [comment]
I'm going to take a look on a device and on a simulator

**Comment by mandel-macaque** [comment]
Tested with the current master, everything works as expected. Could have been either related to the arch fix or to the issues in my machine.
