### ISSUE TITLE
[wasm] `testResults.xml` can end up with zero results if some particular tests are part of the run

### ISSUE THREAD

**Issue by radical** [dotnet/xharness#903]
This can be seen with `System.IO.FileSystem.Tests` in `dotnet/runtime`. 

This is from a [rolling build](https://dev.azure.com/dnceng/public/_build/results?buildId=1817295&view=logs&j=11c5c840-d20a-5536-428b-70d8cd9c6259&t=73598586-463f-5241-5dc8-b8ffdebf8b89), and the [results xml](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f7aa47e64eb44eda8f/WasmTestOnBrowser-System.IO.FileSystem.Tests/1/xharness-output/testResults.xml?helixlogtype=result) show:

```xml
<?xml version="1.0" encoding="utf-8"?>
<assemblies>
  <assembly name="System.IO.FileSystem.Tests.dll" environment="32-bit .NET  [collection-per-class, non-parallel]" test-framework="xUnit.net 2.4.2.0" run-date="2022-06-10" run-time="09:12:06">
    <errors />
  </assembly>
</assemblies>
```

This doesn't even have the counts for the tests run, passed etc. But the [console output](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f7aa47e64eb44eda8f/WasmTestOnBrowser-System.IO.FileSystem.Tests/1/console.2bb287c0.log?helixlogtype=result) has:

`Total: 5542, Errors: 0, Failed: 0, Skipped: 208, Time: 110.0339999s`

I was able to narrow it down to `System.IO.Tests.File_ReadWriteAllTextAsync.OutputIsTheSameAsForStreamWriter_OverwriteAsync` this test in particular. If that is part of the test run, then the xml doesn't get any results.

To reproduce the issue:
- in a `dotnet/runtime` codespace, run:
`$ ./dotnet.sh build src/libraries/System.IO.FileSystem/tests/System.IO.FileSystem.Tests.csproj /p:Configuration=Release /p:TargetOS=Browser /p:TargetArchitecture=wasm /t:Test`

The output will show:
```
  info: Received expected 289 of /workspaces/runtime/artifacts/bin/System.IO.FileSystem.Tests/Release/net7.0-browser/browser-wasm/AppBundle/xharness-output/testResults.xml
```

And that's the empty xml. You can add `WasmXHarnessArgs="-v diag"` to see that the tests are indeed running.

**Comment by radical** [comment]
cc @premun @maraf

**Comment by akoeplinger** [comment]
@radical I reproduced this, but when I disable the test you mentioned and even the other ones relying on `OutputIsTheSameAsForStreamWriter_Args` the testResult.xml still doesn't have any data in it. Did it have data for you after disabling the test?

**Comment by premun** [comment]
I think this is the code we're using?
https://github.com/dotnet/xharness/blob/a194f1af53e91a278e1f17d176d3cd6c1b73b7e0/src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs#L133

Seems like this `Xunit2` class accepts the `DelegatingXmlCreationSink` which should fill the assembly element (`resultsXmlAssembly`) which is then appended onto the root `_assembliesElement` of the XML which is then written into the file.

Seems like filling of the element happens in the Xunit code only?

**Comment by radical** [comment]
> @radical I reproduced this, but when I disable the test you mentioned and even the other ones relying on `OutputIsTheSameAsForStreamWriter_Args` the testResult.xml still doesn't have any data in it. Did it have data for you after disabling the test?

It was more tests, like the whole `XUnitClassName=System.IO.Tests.File_ReadWriteAllTextAsync`. And I think the related `File_ReadWriteAllText`. At a glance, it seemed like it was with tests that had unicode characters in their "name"(inline/member data).

**Comment by akoeplinger** [comment]
I figured out the issue, it seems to be a regression from https://github.com/dotnet/xharness/pull/790. If I put the while loop back I get the correct result xml back.

**Comment by akoeplinger** [comment]
Opened a PR with a fix: https://github.com/dotnet/xharness/pull/906
