### ISSUE TITLE
[wasm] CI running very old tests from `dotnet/runtime`

### ISSUE THREAD

**Issue by radical** [dotnet/xharness#920]
For the WASM leg of CI, we get `System.Reflection.Tests.zip` from https://netcorenativeassets.blob.core.windows.net/resource-packages/external/wasm/System.Reflection.Extensions.Tests.zip . But those tests are very old - from `Jun 26 2020` to be exact.

1. Is there a better way to do this? Can this file get uploaded to that url from rolling builds?
2. In addition, should we add a new (manual trigger) pipeline for PRs to run the `dotnet/runtime`/wasm library tests with the newly built xharness?

cc @akoeplinger @premun

**Comment by radical** [comment]
Also, the current setup only runs tests with `v8`, so it's missing testing for browser, and nodejs.

```diff
diff --git a/tests/integration-tests/WASM/WASM.Helix.SDK.Tests.proj b/tests/integration-tests/WASM/WASM.Helix.SDK.Tests.proj
index 555941d..6375329 100644
--- a/tests/integration-tests/WASM/WASM.Helix.SDK.Tests.proj
+++ b/tests/integration-tests/WASM/WASM.Helix.SDK.Tests.proj
@@ -3,6 +3,7 @@

   <ItemGroup>
     <HelixTargetQueue Include="ubuntu.2004.amd64.open"/>
+    <Scenarios Include="normal;WasmTestOnBrowser;WasmTestOnNodeJs" />
   </ItemGroup>

   <PropertyGroup>
@@ -17,10 +18,13 @@
     <Message Text="Downloaded @(TestPayloadArchive) for XHarness Test purposes" Importance="High" />

     <ItemGroup>
-      <HelixWorkItem Include="System.Reflection.Extensions.Tests">
+      <HelixWorkItem Include="%(Scenario.Identity)-System.Reflection.Extensions.Tests">
         <Command>cd "$HELIX_WORKITEM_PAYLOAD/System.Reflection.Extensions.Tests" &amp;&amp; dotnet exec $XHARNESS_CLI_PATH wasm test --engine=V8 --js-file=runtime.js -v --output-directory="$HELIX_WORKITEM_UPLOAD_ROOT" -- --enable-gc --run WasmTestRunner.dll System.Reflection.Extensions.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing</Command>
         <PayloadArchive>@(TestPayloadArchive)</PayloadArchive>
         <Timeout>00:10:00</Timeout>
+
+        <PreCommands Condition="'$(OS)' == 'Windows_NT'">set Scenario=%(Scenarios.Identity)</PreCommands>
+        <PreCommands Condition="'$(OS)' != 'Windows_NT'">export Scenario=%(Scenarios.Identity)</PreCommands>
       </HelixWorkItem>
     </ItemGroup>
   </Target>
```

- this will need chrome+chromedriver+node though

**Comment by akoeplinger** [comment]
We can certainly update the System.Reflection.Tests.zip (@premun would need to handle that).

About the browser/node scenarios they should just work given we running these on Helix right?

**Comment by radical** [comment]
> About the browser/node scenarios they should just work given we running these on Helix right?

Do we already provision chrome+chromedriver+node? From `dotnet/runtime`, we send them as payloads to helix.

**Comment by premun** [comment]
I agree this has value and should be updated but I don't have the expertise with WASM payloads.

I am happy to help uploading the new apps but I don't understand how to construct the whole payload for that test.

**Comment by premun** [comment]
There was also this - https://github.com/dotnet/xharness/issues/302

**Comment by radical** [comment]
> I am happy to help uploading the new apps but I don't understand how to construct the whole payload for that test.

1. checkout `dotnet/runtime`
2. `make -C src/mono/wasm provision-wasm build-all`
3. `./dotnet.sh build /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:ArchiveTests=true /p:Configuration=Release src/libraries/System.Reflection/tests/System.Reflection.Tests.csproj`
4. The bundle will be at `artifacts/helix/tests/Browser.AnyCPU.Release/System.Reflection.Tests.zip`

**Comment by radical** [comment]
@premun can we make a recent build available for this? I can look at updating the CI to use that, or any browser tests that we want to run.

**Comment by premun** [comment]
@radical I'm more than happy to do that but I tried last time and realize I don't even have runtime set up at the moment. Would it be possible you build the binary for me, share it (over Teams) and I can upload it and help you wire it in the CI?

**Comment by radical** [comment]
I can build it on codespaces, and share with you.

**Comment by pavelsavara** [comment]
@premun please upload [this](https://helixde107v0xdeko0k025g8.blob.core.windows.net/helix-job-6aaffa0d-0498-4d79-bb43-8e5d76e7b4037bf6d018b48404188/Common.Tests.zip) into `https://netcorenativeassets.blob.core.windows.net/resource-packages/external/wasm/ `

**Comment by radical** [comment]
It would be useful to have the http functional tests too, since they use the webserver middleware logic.
